
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CartRecipeSync` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CartRecipeSync
 * 
 */
export type CartRecipeSyncModel = runtime.Types.Result.DefaultSelection<Prisma.$CartRecipeSyncPayload>

export type AggregateCartRecipeSync = {
  _count: CartRecipeSyncCountAggregateOutputType | null
  _avg: CartRecipeSyncAvgAggregateOutputType | null
  _sum: CartRecipeSyncSumAggregateOutputType | null
  _min: CartRecipeSyncMinAggregateOutputType | null
  _max: CartRecipeSyncMaxAggregateOutputType | null
}

export type CartRecipeSyncAvgAggregateOutputType = {
  syncedOutputQuantity: runtime.Decimal | null
}

export type CartRecipeSyncSumAggregateOutputType = {
  syncedOutputQuantity: runtime.Decimal | null
}

export type CartRecipeSyncMinAggregateOutputType = {
  id: string | null
  cartId: string | null
  recipeId: string | null
  recipeTitle: string | null
  syncedOutputQuantity: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CartRecipeSyncMaxAggregateOutputType = {
  id: string | null
  cartId: string | null
  recipeId: string | null
  recipeTitle: string | null
  syncedOutputQuantity: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CartRecipeSyncCountAggregateOutputType = {
  id: number
  cartId: number
  recipeId: number
  recipeTitle: number
  syncedOutputQuantity: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CartRecipeSyncAvgAggregateInputType = {
  syncedOutputQuantity?: true
}

export type CartRecipeSyncSumAggregateInputType = {
  syncedOutputQuantity?: true
}

export type CartRecipeSyncMinAggregateInputType = {
  id?: true
  cartId?: true
  recipeId?: true
  recipeTitle?: true
  syncedOutputQuantity?: true
  createdAt?: true
  updatedAt?: true
}

export type CartRecipeSyncMaxAggregateInputType = {
  id?: true
  cartId?: true
  recipeId?: true
  recipeTitle?: true
  syncedOutputQuantity?: true
  createdAt?: true
  updatedAt?: true
}

export type CartRecipeSyncCountAggregateInputType = {
  id?: true
  cartId?: true
  recipeId?: true
  recipeTitle?: true
  syncedOutputQuantity?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CartRecipeSyncAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CartRecipeSync to aggregate.
   */
  where?: Prisma.CartRecipeSyncWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CartRecipeSyncs to fetch.
   */
  orderBy?: Prisma.CartRecipeSyncOrderByWithRelationInput | Prisma.CartRecipeSyncOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CartRecipeSyncWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CartRecipeSyncs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CartRecipeSyncs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CartRecipeSyncs
  **/
  _count?: true | CartRecipeSyncCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CartRecipeSyncAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CartRecipeSyncSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CartRecipeSyncMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CartRecipeSyncMaxAggregateInputType
}

export type GetCartRecipeSyncAggregateType<T extends CartRecipeSyncAggregateArgs> = {
      [P in keyof T & keyof AggregateCartRecipeSync]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCartRecipeSync[P]>
    : Prisma.GetScalarType<T[P], AggregateCartRecipeSync[P]>
}




export type CartRecipeSyncGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CartRecipeSyncWhereInput
  orderBy?: Prisma.CartRecipeSyncOrderByWithAggregationInput | Prisma.CartRecipeSyncOrderByWithAggregationInput[]
  by: Prisma.CartRecipeSyncScalarFieldEnum[] | Prisma.CartRecipeSyncScalarFieldEnum
  having?: Prisma.CartRecipeSyncScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CartRecipeSyncCountAggregateInputType | true
  _avg?: CartRecipeSyncAvgAggregateInputType
  _sum?: CartRecipeSyncSumAggregateInputType
  _min?: CartRecipeSyncMinAggregateInputType
  _max?: CartRecipeSyncMaxAggregateInputType
}

export type CartRecipeSyncGroupByOutputType = {
  id: string
  cartId: string
  recipeId: string
  recipeTitle: string | null
  syncedOutputQuantity: runtime.Decimal
  createdAt: Date
  updatedAt: Date
  _count: CartRecipeSyncCountAggregateOutputType | null
  _avg: CartRecipeSyncAvgAggregateOutputType | null
  _sum: CartRecipeSyncSumAggregateOutputType | null
  _min: CartRecipeSyncMinAggregateOutputType | null
  _max: CartRecipeSyncMaxAggregateOutputType | null
}

export type GetCartRecipeSyncGroupByPayload<T extends CartRecipeSyncGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CartRecipeSyncGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CartRecipeSyncGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CartRecipeSyncGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CartRecipeSyncGroupByOutputType[P]>
      }
    >
  >



export type CartRecipeSyncWhereInput = {
  AND?: Prisma.CartRecipeSyncWhereInput | Prisma.CartRecipeSyncWhereInput[]
  OR?: Prisma.CartRecipeSyncWhereInput[]
  NOT?: Prisma.CartRecipeSyncWhereInput | Prisma.CartRecipeSyncWhereInput[]
  id?: Prisma.StringFilter<"CartRecipeSync"> | string
  cartId?: Prisma.StringFilter<"CartRecipeSync"> | string
  recipeId?: Prisma.StringFilter<"CartRecipeSync"> | string
  recipeTitle?: Prisma.StringNullableFilter<"CartRecipeSync"> | string | null
  syncedOutputQuantity?: Prisma.DecimalFilter<"CartRecipeSync"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"CartRecipeSync"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CartRecipeSync"> | Date | string
  cart?: Prisma.XOR<Prisma.CartScalarRelationFilter, Prisma.CartWhereInput>
}

export type CartRecipeSyncOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  cartId?: Prisma.SortOrder
  recipeId?: Prisma.SortOrder
  recipeTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  syncedOutputQuantity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  cart?: Prisma.CartOrderByWithRelationInput
}

export type CartRecipeSyncWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  cartId_recipeId?: Prisma.CartRecipeSyncCartIdRecipeIdCompoundUniqueInput
  AND?: Prisma.CartRecipeSyncWhereInput | Prisma.CartRecipeSyncWhereInput[]
  OR?: Prisma.CartRecipeSyncWhereInput[]
  NOT?: Prisma.CartRecipeSyncWhereInput | Prisma.CartRecipeSyncWhereInput[]
  cartId?: Prisma.StringFilter<"CartRecipeSync"> | string
  recipeId?: Prisma.StringFilter<"CartRecipeSync"> | string
  recipeTitle?: Prisma.StringNullableFilter<"CartRecipeSync"> | string | null
  syncedOutputQuantity?: Prisma.DecimalFilter<"CartRecipeSync"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"CartRecipeSync"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CartRecipeSync"> | Date | string
  cart?: Prisma.XOR<Prisma.CartScalarRelationFilter, Prisma.CartWhereInput>
}, "id" | "cartId_recipeId">

export type CartRecipeSyncOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  cartId?: Prisma.SortOrder
  recipeId?: Prisma.SortOrder
  recipeTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  syncedOutputQuantity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CartRecipeSyncCountOrderByAggregateInput
  _avg?: Prisma.CartRecipeSyncAvgOrderByAggregateInput
  _max?: Prisma.CartRecipeSyncMaxOrderByAggregateInput
  _min?: Prisma.CartRecipeSyncMinOrderByAggregateInput
  _sum?: Prisma.CartRecipeSyncSumOrderByAggregateInput
}

export type CartRecipeSyncScalarWhereWithAggregatesInput = {
  AND?: Prisma.CartRecipeSyncScalarWhereWithAggregatesInput | Prisma.CartRecipeSyncScalarWhereWithAggregatesInput[]
  OR?: Prisma.CartRecipeSyncScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CartRecipeSyncScalarWhereWithAggregatesInput | Prisma.CartRecipeSyncScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CartRecipeSync"> | string
  cartId?: Prisma.StringWithAggregatesFilter<"CartRecipeSync"> | string
  recipeId?: Prisma.StringWithAggregatesFilter<"CartRecipeSync"> | string
  recipeTitle?: Prisma.StringNullableWithAggregatesFilter<"CartRecipeSync"> | string | null
  syncedOutputQuantity?: Prisma.DecimalWithAggregatesFilter<"CartRecipeSync"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CartRecipeSync"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CartRecipeSync"> | Date | string
}

export type CartRecipeSyncCreateInput = {
  id?: string
  recipeId: string
  recipeTitle?: string | null
  syncedOutputQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  cart: Prisma.CartCreateNestedOneWithoutRecipeSyncsInput
}

export type CartRecipeSyncUncheckedCreateInput = {
  id?: string
  cartId: string
  recipeId: string
  recipeTitle?: string | null
  syncedOutputQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CartRecipeSyncUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipeId?: Prisma.StringFieldUpdateOperationsInput | string
  recipeTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  syncedOutputQuantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cart?: Prisma.CartUpdateOneRequiredWithoutRecipeSyncsNestedInput
}

export type CartRecipeSyncUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  cartId?: Prisma.StringFieldUpdateOperationsInput | string
  recipeId?: Prisma.StringFieldUpdateOperationsInput | string
  recipeTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  syncedOutputQuantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CartRecipeSyncCreateManyInput = {
  id?: string
  cartId: string
  recipeId: string
  recipeTitle?: string | null
  syncedOutputQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CartRecipeSyncUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipeId?: Prisma.StringFieldUpdateOperationsInput | string
  recipeTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  syncedOutputQuantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CartRecipeSyncUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  cartId?: Prisma.StringFieldUpdateOperationsInput | string
  recipeId?: Prisma.StringFieldUpdateOperationsInput | string
  recipeTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  syncedOutputQuantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CartRecipeSyncListRelationFilter = {
  every?: Prisma.CartRecipeSyncWhereInput
  some?: Prisma.CartRecipeSyncWhereInput
  none?: Prisma.CartRecipeSyncWhereInput
}

export type CartRecipeSyncOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CartRecipeSyncCartIdRecipeIdCompoundUniqueInput = {
  cartId: string
  recipeId: string
}

export type CartRecipeSyncCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cartId?: Prisma.SortOrder
  recipeId?: Prisma.SortOrder
  recipeTitle?: Prisma.SortOrder
  syncedOutputQuantity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CartRecipeSyncAvgOrderByAggregateInput = {
  syncedOutputQuantity?: Prisma.SortOrder
}

export type CartRecipeSyncMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cartId?: Prisma.SortOrder
  recipeId?: Prisma.SortOrder
  recipeTitle?: Prisma.SortOrder
  syncedOutputQuantity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CartRecipeSyncMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cartId?: Prisma.SortOrder
  recipeId?: Prisma.SortOrder
  recipeTitle?: Prisma.SortOrder
  syncedOutputQuantity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CartRecipeSyncSumOrderByAggregateInput = {
  syncedOutputQuantity?: Prisma.SortOrder
}

export type CartRecipeSyncCreateNestedManyWithoutCartInput = {
  create?: Prisma.XOR<Prisma.CartRecipeSyncCreateWithoutCartInput, Prisma.CartRecipeSyncUncheckedCreateWithoutCartInput> | Prisma.CartRecipeSyncCreateWithoutCartInput[] | Prisma.CartRecipeSyncUncheckedCreateWithoutCartInput[]
  connectOrCreate?: Prisma.CartRecipeSyncCreateOrConnectWithoutCartInput | Prisma.CartRecipeSyncCreateOrConnectWithoutCartInput[]
  createMany?: Prisma.CartRecipeSyncCreateManyCartInputEnvelope
  connect?: Prisma.CartRecipeSyncWhereUniqueInput | Prisma.CartRecipeSyncWhereUniqueInput[]
}

export type CartRecipeSyncUncheckedCreateNestedManyWithoutCartInput = {
  create?: Prisma.XOR<Prisma.CartRecipeSyncCreateWithoutCartInput, Prisma.CartRecipeSyncUncheckedCreateWithoutCartInput> | Prisma.CartRecipeSyncCreateWithoutCartInput[] | Prisma.CartRecipeSyncUncheckedCreateWithoutCartInput[]
  connectOrCreate?: Prisma.CartRecipeSyncCreateOrConnectWithoutCartInput | Prisma.CartRecipeSyncCreateOrConnectWithoutCartInput[]
  createMany?: Prisma.CartRecipeSyncCreateManyCartInputEnvelope
  connect?: Prisma.CartRecipeSyncWhereUniqueInput | Prisma.CartRecipeSyncWhereUniqueInput[]
}

export type CartRecipeSyncUpdateManyWithoutCartNestedInput = {
  create?: Prisma.XOR<Prisma.CartRecipeSyncCreateWithoutCartInput, Prisma.CartRecipeSyncUncheckedCreateWithoutCartInput> | Prisma.CartRecipeSyncCreateWithoutCartInput[] | Prisma.CartRecipeSyncUncheckedCreateWithoutCartInput[]
  connectOrCreate?: Prisma.CartRecipeSyncCreateOrConnectWithoutCartInput | Prisma.CartRecipeSyncCreateOrConnectWithoutCartInput[]
  upsert?: Prisma.CartRecipeSyncUpsertWithWhereUniqueWithoutCartInput | Prisma.CartRecipeSyncUpsertWithWhereUniqueWithoutCartInput[]
  createMany?: Prisma.CartRecipeSyncCreateManyCartInputEnvelope
  set?: Prisma.CartRecipeSyncWhereUniqueInput | Prisma.CartRecipeSyncWhereUniqueInput[]
  disconnect?: Prisma.CartRecipeSyncWhereUniqueInput | Prisma.CartRecipeSyncWhereUniqueInput[]
  delete?: Prisma.CartRecipeSyncWhereUniqueInput | Prisma.CartRecipeSyncWhereUniqueInput[]
  connect?: Prisma.CartRecipeSyncWhereUniqueInput | Prisma.CartRecipeSyncWhereUniqueInput[]
  update?: Prisma.CartRecipeSyncUpdateWithWhereUniqueWithoutCartInput | Prisma.CartRecipeSyncUpdateWithWhereUniqueWithoutCartInput[]
  updateMany?: Prisma.CartRecipeSyncUpdateManyWithWhereWithoutCartInput | Prisma.CartRecipeSyncUpdateManyWithWhereWithoutCartInput[]
  deleteMany?: Prisma.CartRecipeSyncScalarWhereInput | Prisma.CartRecipeSyncScalarWhereInput[]
}

export type CartRecipeSyncUncheckedUpdateManyWithoutCartNestedInput = {
  create?: Prisma.XOR<Prisma.CartRecipeSyncCreateWithoutCartInput, Prisma.CartRecipeSyncUncheckedCreateWithoutCartInput> | Prisma.CartRecipeSyncCreateWithoutCartInput[] | Prisma.CartRecipeSyncUncheckedCreateWithoutCartInput[]
  connectOrCreate?: Prisma.CartRecipeSyncCreateOrConnectWithoutCartInput | Prisma.CartRecipeSyncCreateOrConnectWithoutCartInput[]
  upsert?: Prisma.CartRecipeSyncUpsertWithWhereUniqueWithoutCartInput | Prisma.CartRecipeSyncUpsertWithWhereUniqueWithoutCartInput[]
  createMany?: Prisma.CartRecipeSyncCreateManyCartInputEnvelope
  set?: Prisma.CartRecipeSyncWhereUniqueInput | Prisma.CartRecipeSyncWhereUniqueInput[]
  disconnect?: Prisma.CartRecipeSyncWhereUniqueInput | Prisma.CartRecipeSyncWhereUniqueInput[]
  delete?: Prisma.CartRecipeSyncWhereUniqueInput | Prisma.CartRecipeSyncWhereUniqueInput[]
  connect?: Prisma.CartRecipeSyncWhereUniqueInput | Prisma.CartRecipeSyncWhereUniqueInput[]
  update?: Prisma.CartRecipeSyncUpdateWithWhereUniqueWithoutCartInput | Prisma.CartRecipeSyncUpdateWithWhereUniqueWithoutCartInput[]
  updateMany?: Prisma.CartRecipeSyncUpdateManyWithWhereWithoutCartInput | Prisma.CartRecipeSyncUpdateManyWithWhereWithoutCartInput[]
  deleteMany?: Prisma.CartRecipeSyncScalarWhereInput | Prisma.CartRecipeSyncScalarWhereInput[]
}

export type CartRecipeSyncCreateWithoutCartInput = {
  id?: string
  recipeId: string
  recipeTitle?: string | null
  syncedOutputQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CartRecipeSyncUncheckedCreateWithoutCartInput = {
  id?: string
  recipeId: string
  recipeTitle?: string | null
  syncedOutputQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CartRecipeSyncCreateOrConnectWithoutCartInput = {
  where: Prisma.CartRecipeSyncWhereUniqueInput
  create: Prisma.XOR<Prisma.CartRecipeSyncCreateWithoutCartInput, Prisma.CartRecipeSyncUncheckedCreateWithoutCartInput>
}

export type CartRecipeSyncCreateManyCartInputEnvelope = {
  data: Prisma.CartRecipeSyncCreateManyCartInput | Prisma.CartRecipeSyncCreateManyCartInput[]
  skipDuplicates?: boolean
}

export type CartRecipeSyncUpsertWithWhereUniqueWithoutCartInput = {
  where: Prisma.CartRecipeSyncWhereUniqueInput
  update: Prisma.XOR<Prisma.CartRecipeSyncUpdateWithoutCartInput, Prisma.CartRecipeSyncUncheckedUpdateWithoutCartInput>
  create: Prisma.XOR<Prisma.CartRecipeSyncCreateWithoutCartInput, Prisma.CartRecipeSyncUncheckedCreateWithoutCartInput>
}

export type CartRecipeSyncUpdateWithWhereUniqueWithoutCartInput = {
  where: Prisma.CartRecipeSyncWhereUniqueInput
  data: Prisma.XOR<Prisma.CartRecipeSyncUpdateWithoutCartInput, Prisma.CartRecipeSyncUncheckedUpdateWithoutCartInput>
}

export type CartRecipeSyncUpdateManyWithWhereWithoutCartInput = {
  where: Prisma.CartRecipeSyncScalarWhereInput
  data: Prisma.XOR<Prisma.CartRecipeSyncUpdateManyMutationInput, Prisma.CartRecipeSyncUncheckedUpdateManyWithoutCartInput>
}

export type CartRecipeSyncScalarWhereInput = {
  AND?: Prisma.CartRecipeSyncScalarWhereInput | Prisma.CartRecipeSyncScalarWhereInput[]
  OR?: Prisma.CartRecipeSyncScalarWhereInput[]
  NOT?: Prisma.CartRecipeSyncScalarWhereInput | Prisma.CartRecipeSyncScalarWhereInput[]
  id?: Prisma.StringFilter<"CartRecipeSync"> | string
  cartId?: Prisma.StringFilter<"CartRecipeSync"> | string
  recipeId?: Prisma.StringFilter<"CartRecipeSync"> | string
  recipeTitle?: Prisma.StringNullableFilter<"CartRecipeSync"> | string | null
  syncedOutputQuantity?: Prisma.DecimalFilter<"CartRecipeSync"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"CartRecipeSync"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CartRecipeSync"> | Date | string
}

export type CartRecipeSyncCreateManyCartInput = {
  id?: string
  recipeId: string
  recipeTitle?: string | null
  syncedOutputQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CartRecipeSyncUpdateWithoutCartInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipeId?: Prisma.StringFieldUpdateOperationsInput | string
  recipeTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  syncedOutputQuantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CartRecipeSyncUncheckedUpdateWithoutCartInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipeId?: Prisma.StringFieldUpdateOperationsInput | string
  recipeTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  syncedOutputQuantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CartRecipeSyncUncheckedUpdateManyWithoutCartInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipeId?: Prisma.StringFieldUpdateOperationsInput | string
  recipeTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  syncedOutputQuantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CartRecipeSyncSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cartId?: boolean
  recipeId?: boolean
  recipeTitle?: boolean
  syncedOutputQuantity?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  cart?: boolean | Prisma.CartDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cartRecipeSync"]>

export type CartRecipeSyncSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cartId?: boolean
  recipeId?: boolean
  recipeTitle?: boolean
  syncedOutputQuantity?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  cart?: boolean | Prisma.CartDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cartRecipeSync"]>

export type CartRecipeSyncSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cartId?: boolean
  recipeId?: boolean
  recipeTitle?: boolean
  syncedOutputQuantity?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  cart?: boolean | Prisma.CartDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cartRecipeSync"]>

export type CartRecipeSyncSelectScalar = {
  id?: boolean
  cartId?: boolean
  recipeId?: boolean
  recipeTitle?: boolean
  syncedOutputQuantity?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CartRecipeSyncOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "cartId" | "recipeId" | "recipeTitle" | "syncedOutputQuantity" | "createdAt" | "updatedAt", ExtArgs["result"]["cartRecipeSync"]>
export type CartRecipeSyncInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cart?: boolean | Prisma.CartDefaultArgs<ExtArgs>
}
export type CartRecipeSyncIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cart?: boolean | Prisma.CartDefaultArgs<ExtArgs>
}
export type CartRecipeSyncIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cart?: boolean | Prisma.CartDefaultArgs<ExtArgs>
}

export type $CartRecipeSyncPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CartRecipeSync"
  objects: {
    cart: Prisma.$CartPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    cartId: string
    recipeId: string
    recipeTitle: string | null
    syncedOutputQuantity: runtime.Decimal
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["cartRecipeSync"]>
  composites: {}
}

export type CartRecipeSyncGetPayload<S extends boolean | null | undefined | CartRecipeSyncDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CartRecipeSyncPayload, S>

export type CartRecipeSyncCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CartRecipeSyncFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CartRecipeSyncCountAggregateInputType | true
  }

export interface CartRecipeSyncDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CartRecipeSync'], meta: { name: 'CartRecipeSync' } }
  /**
   * Find zero or one CartRecipeSync that matches the filter.
   * @param {CartRecipeSyncFindUniqueArgs} args - Arguments to find a CartRecipeSync
   * @example
   * // Get one CartRecipeSync
   * const cartRecipeSync = await prisma.cartRecipeSync.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CartRecipeSyncFindUniqueArgs>(args: Prisma.SelectSubset<T, CartRecipeSyncFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CartRecipeSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeSyncPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CartRecipeSync that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CartRecipeSyncFindUniqueOrThrowArgs} args - Arguments to find a CartRecipeSync
   * @example
   * // Get one CartRecipeSync
   * const cartRecipeSync = await prisma.cartRecipeSync.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CartRecipeSyncFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CartRecipeSyncFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CartRecipeSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeSyncPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CartRecipeSync that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartRecipeSyncFindFirstArgs} args - Arguments to find a CartRecipeSync
   * @example
   * // Get one CartRecipeSync
   * const cartRecipeSync = await prisma.cartRecipeSync.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CartRecipeSyncFindFirstArgs>(args?: Prisma.SelectSubset<T, CartRecipeSyncFindFirstArgs<ExtArgs>>): Prisma.Prisma__CartRecipeSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeSyncPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CartRecipeSync that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartRecipeSyncFindFirstOrThrowArgs} args - Arguments to find a CartRecipeSync
   * @example
   * // Get one CartRecipeSync
   * const cartRecipeSync = await prisma.cartRecipeSync.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CartRecipeSyncFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CartRecipeSyncFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CartRecipeSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeSyncPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CartRecipeSyncs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartRecipeSyncFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CartRecipeSyncs
   * const cartRecipeSyncs = await prisma.cartRecipeSync.findMany()
   * 
   * // Get first 10 CartRecipeSyncs
   * const cartRecipeSyncs = await prisma.cartRecipeSync.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const cartRecipeSyncWithIdOnly = await prisma.cartRecipeSync.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CartRecipeSyncFindManyArgs>(args?: Prisma.SelectSubset<T, CartRecipeSyncFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CartRecipeSyncPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CartRecipeSync.
   * @param {CartRecipeSyncCreateArgs} args - Arguments to create a CartRecipeSync.
   * @example
   * // Create one CartRecipeSync
   * const CartRecipeSync = await prisma.cartRecipeSync.create({
   *   data: {
   *     // ... data to create a CartRecipeSync
   *   }
   * })
   * 
   */
  create<T extends CartRecipeSyncCreateArgs>(args: Prisma.SelectSubset<T, CartRecipeSyncCreateArgs<ExtArgs>>): Prisma.Prisma__CartRecipeSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeSyncPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CartRecipeSyncs.
   * @param {CartRecipeSyncCreateManyArgs} args - Arguments to create many CartRecipeSyncs.
   * @example
   * // Create many CartRecipeSyncs
   * const cartRecipeSync = await prisma.cartRecipeSync.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CartRecipeSyncCreateManyArgs>(args?: Prisma.SelectSubset<T, CartRecipeSyncCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CartRecipeSyncs and returns the data saved in the database.
   * @param {CartRecipeSyncCreateManyAndReturnArgs} args - Arguments to create many CartRecipeSyncs.
   * @example
   * // Create many CartRecipeSyncs
   * const cartRecipeSync = await prisma.cartRecipeSync.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CartRecipeSyncs and only return the `id`
   * const cartRecipeSyncWithIdOnly = await prisma.cartRecipeSync.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CartRecipeSyncCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CartRecipeSyncCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CartRecipeSyncPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CartRecipeSync.
   * @param {CartRecipeSyncDeleteArgs} args - Arguments to delete one CartRecipeSync.
   * @example
   * // Delete one CartRecipeSync
   * const CartRecipeSync = await prisma.cartRecipeSync.delete({
   *   where: {
   *     // ... filter to delete one CartRecipeSync
   *   }
   * })
   * 
   */
  delete<T extends CartRecipeSyncDeleteArgs>(args: Prisma.SelectSubset<T, CartRecipeSyncDeleteArgs<ExtArgs>>): Prisma.Prisma__CartRecipeSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeSyncPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CartRecipeSync.
   * @param {CartRecipeSyncUpdateArgs} args - Arguments to update one CartRecipeSync.
   * @example
   * // Update one CartRecipeSync
   * const cartRecipeSync = await prisma.cartRecipeSync.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CartRecipeSyncUpdateArgs>(args: Prisma.SelectSubset<T, CartRecipeSyncUpdateArgs<ExtArgs>>): Prisma.Prisma__CartRecipeSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeSyncPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CartRecipeSyncs.
   * @param {CartRecipeSyncDeleteManyArgs} args - Arguments to filter CartRecipeSyncs to delete.
   * @example
   * // Delete a few CartRecipeSyncs
   * const { count } = await prisma.cartRecipeSync.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CartRecipeSyncDeleteManyArgs>(args?: Prisma.SelectSubset<T, CartRecipeSyncDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CartRecipeSyncs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartRecipeSyncUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CartRecipeSyncs
   * const cartRecipeSync = await prisma.cartRecipeSync.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CartRecipeSyncUpdateManyArgs>(args: Prisma.SelectSubset<T, CartRecipeSyncUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CartRecipeSyncs and returns the data updated in the database.
   * @param {CartRecipeSyncUpdateManyAndReturnArgs} args - Arguments to update many CartRecipeSyncs.
   * @example
   * // Update many CartRecipeSyncs
   * const cartRecipeSync = await prisma.cartRecipeSync.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CartRecipeSyncs and only return the `id`
   * const cartRecipeSyncWithIdOnly = await prisma.cartRecipeSync.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CartRecipeSyncUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CartRecipeSyncUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CartRecipeSyncPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CartRecipeSync.
   * @param {CartRecipeSyncUpsertArgs} args - Arguments to update or create a CartRecipeSync.
   * @example
   * // Update or create a CartRecipeSync
   * const cartRecipeSync = await prisma.cartRecipeSync.upsert({
   *   create: {
   *     // ... data to create a CartRecipeSync
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CartRecipeSync we want to update
   *   }
   * })
   */
  upsert<T extends CartRecipeSyncUpsertArgs>(args: Prisma.SelectSubset<T, CartRecipeSyncUpsertArgs<ExtArgs>>): Prisma.Prisma__CartRecipeSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeSyncPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CartRecipeSyncs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartRecipeSyncCountArgs} args - Arguments to filter CartRecipeSyncs to count.
   * @example
   * // Count the number of CartRecipeSyncs
   * const count = await prisma.cartRecipeSync.count({
   *   where: {
   *     // ... the filter for the CartRecipeSyncs we want to count
   *   }
   * })
  **/
  count<T extends CartRecipeSyncCountArgs>(
    args?: Prisma.Subset<T, CartRecipeSyncCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CartRecipeSyncCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CartRecipeSync.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartRecipeSyncAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CartRecipeSyncAggregateArgs>(args: Prisma.Subset<T, CartRecipeSyncAggregateArgs>): Prisma.PrismaPromise<GetCartRecipeSyncAggregateType<T>>

  /**
   * Group by CartRecipeSync.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartRecipeSyncGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CartRecipeSyncGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CartRecipeSyncGroupByArgs['orderBy'] }
      : { orderBy?: CartRecipeSyncGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CartRecipeSyncGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCartRecipeSyncGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CartRecipeSync model
 */
readonly fields: CartRecipeSyncFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CartRecipeSync.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CartRecipeSyncClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  cart<T extends Prisma.CartDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CartDefaultArgs<ExtArgs>>): Prisma.Prisma__CartClient<runtime.Types.Result.GetResult<Prisma.$CartPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CartRecipeSync model
 */
export interface CartRecipeSyncFieldRefs {
  readonly id: Prisma.FieldRef<"CartRecipeSync", 'String'>
  readonly cartId: Prisma.FieldRef<"CartRecipeSync", 'String'>
  readonly recipeId: Prisma.FieldRef<"CartRecipeSync", 'String'>
  readonly recipeTitle: Prisma.FieldRef<"CartRecipeSync", 'String'>
  readonly syncedOutputQuantity: Prisma.FieldRef<"CartRecipeSync", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"CartRecipeSync", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CartRecipeSync", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CartRecipeSync findUnique
 */
export type CartRecipeSyncFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeSync
   */
  select?: Prisma.CartRecipeSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeSync
   */
  omit?: Prisma.CartRecipeSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeSyncInclude<ExtArgs> | null
  /**
   * Filter, which CartRecipeSync to fetch.
   */
  where: Prisma.CartRecipeSyncWhereUniqueInput
}

/**
 * CartRecipeSync findUniqueOrThrow
 */
export type CartRecipeSyncFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeSync
   */
  select?: Prisma.CartRecipeSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeSync
   */
  omit?: Prisma.CartRecipeSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeSyncInclude<ExtArgs> | null
  /**
   * Filter, which CartRecipeSync to fetch.
   */
  where: Prisma.CartRecipeSyncWhereUniqueInput
}

/**
 * CartRecipeSync findFirst
 */
export type CartRecipeSyncFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeSync
   */
  select?: Prisma.CartRecipeSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeSync
   */
  omit?: Prisma.CartRecipeSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeSyncInclude<ExtArgs> | null
  /**
   * Filter, which CartRecipeSync to fetch.
   */
  where?: Prisma.CartRecipeSyncWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CartRecipeSyncs to fetch.
   */
  orderBy?: Prisma.CartRecipeSyncOrderByWithRelationInput | Prisma.CartRecipeSyncOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CartRecipeSyncs.
   */
  cursor?: Prisma.CartRecipeSyncWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CartRecipeSyncs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CartRecipeSyncs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CartRecipeSyncs.
   */
  distinct?: Prisma.CartRecipeSyncScalarFieldEnum | Prisma.CartRecipeSyncScalarFieldEnum[]
}

/**
 * CartRecipeSync findFirstOrThrow
 */
export type CartRecipeSyncFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeSync
   */
  select?: Prisma.CartRecipeSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeSync
   */
  omit?: Prisma.CartRecipeSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeSyncInclude<ExtArgs> | null
  /**
   * Filter, which CartRecipeSync to fetch.
   */
  where?: Prisma.CartRecipeSyncWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CartRecipeSyncs to fetch.
   */
  orderBy?: Prisma.CartRecipeSyncOrderByWithRelationInput | Prisma.CartRecipeSyncOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CartRecipeSyncs.
   */
  cursor?: Prisma.CartRecipeSyncWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CartRecipeSyncs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CartRecipeSyncs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CartRecipeSyncs.
   */
  distinct?: Prisma.CartRecipeSyncScalarFieldEnum | Prisma.CartRecipeSyncScalarFieldEnum[]
}

/**
 * CartRecipeSync findMany
 */
export type CartRecipeSyncFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeSync
   */
  select?: Prisma.CartRecipeSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeSync
   */
  omit?: Prisma.CartRecipeSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeSyncInclude<ExtArgs> | null
  /**
   * Filter, which CartRecipeSyncs to fetch.
   */
  where?: Prisma.CartRecipeSyncWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CartRecipeSyncs to fetch.
   */
  orderBy?: Prisma.CartRecipeSyncOrderByWithRelationInput | Prisma.CartRecipeSyncOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CartRecipeSyncs.
   */
  cursor?: Prisma.CartRecipeSyncWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CartRecipeSyncs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CartRecipeSyncs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CartRecipeSyncs.
   */
  distinct?: Prisma.CartRecipeSyncScalarFieldEnum | Prisma.CartRecipeSyncScalarFieldEnum[]
}

/**
 * CartRecipeSync create
 */
export type CartRecipeSyncCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeSync
   */
  select?: Prisma.CartRecipeSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeSync
   */
  omit?: Prisma.CartRecipeSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeSyncInclude<ExtArgs> | null
  /**
   * The data needed to create a CartRecipeSync.
   */
  data: Prisma.XOR<Prisma.CartRecipeSyncCreateInput, Prisma.CartRecipeSyncUncheckedCreateInput>
}

/**
 * CartRecipeSync createMany
 */
export type CartRecipeSyncCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CartRecipeSyncs.
   */
  data: Prisma.CartRecipeSyncCreateManyInput | Prisma.CartRecipeSyncCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CartRecipeSync createManyAndReturn
 */
export type CartRecipeSyncCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeSync
   */
  select?: Prisma.CartRecipeSyncSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeSync
   */
  omit?: Prisma.CartRecipeSyncOmit<ExtArgs> | null
  /**
   * The data used to create many CartRecipeSyncs.
   */
  data: Prisma.CartRecipeSyncCreateManyInput | Prisma.CartRecipeSyncCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeSyncIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CartRecipeSync update
 */
export type CartRecipeSyncUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeSync
   */
  select?: Prisma.CartRecipeSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeSync
   */
  omit?: Prisma.CartRecipeSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeSyncInclude<ExtArgs> | null
  /**
   * The data needed to update a CartRecipeSync.
   */
  data: Prisma.XOR<Prisma.CartRecipeSyncUpdateInput, Prisma.CartRecipeSyncUncheckedUpdateInput>
  /**
   * Choose, which CartRecipeSync to update.
   */
  where: Prisma.CartRecipeSyncWhereUniqueInput
}

/**
 * CartRecipeSync updateMany
 */
export type CartRecipeSyncUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CartRecipeSyncs.
   */
  data: Prisma.XOR<Prisma.CartRecipeSyncUpdateManyMutationInput, Prisma.CartRecipeSyncUncheckedUpdateManyInput>
  /**
   * Filter which CartRecipeSyncs to update
   */
  where?: Prisma.CartRecipeSyncWhereInput
  /**
   * Limit how many CartRecipeSyncs to update.
   */
  limit?: number
}

/**
 * CartRecipeSync updateManyAndReturn
 */
export type CartRecipeSyncUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeSync
   */
  select?: Prisma.CartRecipeSyncSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeSync
   */
  omit?: Prisma.CartRecipeSyncOmit<ExtArgs> | null
  /**
   * The data used to update CartRecipeSyncs.
   */
  data: Prisma.XOR<Prisma.CartRecipeSyncUpdateManyMutationInput, Prisma.CartRecipeSyncUncheckedUpdateManyInput>
  /**
   * Filter which CartRecipeSyncs to update
   */
  where?: Prisma.CartRecipeSyncWhereInput
  /**
   * Limit how many CartRecipeSyncs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeSyncIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CartRecipeSync upsert
 */
export type CartRecipeSyncUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeSync
   */
  select?: Prisma.CartRecipeSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeSync
   */
  omit?: Prisma.CartRecipeSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeSyncInclude<ExtArgs> | null
  /**
   * The filter to search for the CartRecipeSync to update in case it exists.
   */
  where: Prisma.CartRecipeSyncWhereUniqueInput
  /**
   * In case the CartRecipeSync found by the `where` argument doesn't exist, create a new CartRecipeSync with this data.
   */
  create: Prisma.XOR<Prisma.CartRecipeSyncCreateInput, Prisma.CartRecipeSyncUncheckedCreateInput>
  /**
   * In case the CartRecipeSync was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CartRecipeSyncUpdateInput, Prisma.CartRecipeSyncUncheckedUpdateInput>
}

/**
 * CartRecipeSync delete
 */
export type CartRecipeSyncDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeSync
   */
  select?: Prisma.CartRecipeSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeSync
   */
  omit?: Prisma.CartRecipeSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeSyncInclude<ExtArgs> | null
  /**
   * Filter which CartRecipeSync to delete.
   */
  where: Prisma.CartRecipeSyncWhereUniqueInput
}

/**
 * CartRecipeSync deleteMany
 */
export type CartRecipeSyncDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CartRecipeSyncs to delete
   */
  where?: Prisma.CartRecipeSyncWhereInput
  /**
   * Limit how many CartRecipeSyncs to delete.
   */
  limit?: number
}

/**
 * CartRecipeSync without action
 */
export type CartRecipeSyncDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeSync
   */
  select?: Prisma.CartRecipeSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeSync
   */
  omit?: Prisma.CartRecipeSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeSyncInclude<ExtArgs> | null
}
