
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CartRecipeLineSync` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CartRecipeLineSync
 * 
 */
export type CartRecipeLineSyncModel = runtime.Types.Result.DefaultSelection<Prisma.$CartRecipeLineSyncPayload>

export type AggregateCartRecipeLineSync = {
  _count: CartRecipeLineSyncCountAggregateOutputType | null
  _avg: CartRecipeLineSyncAvgAggregateOutputType | null
  _sum: CartRecipeLineSyncSumAggregateOutputType | null
  _min: CartRecipeLineSyncMinAggregateOutputType | null
  _max: CartRecipeLineSyncMaxAggregateOutputType | null
}

export type CartRecipeLineSyncAvgAggregateOutputType = {
  syncedQuantity: runtime.Decimal | null
}

export type CartRecipeLineSyncSumAggregateOutputType = {
  syncedQuantity: runtime.Decimal | null
}

export type CartRecipeLineSyncMinAggregateOutputType = {
  id: string | null
  syncId: string | null
  recipeIngredientId: string | null
  syncedQuantity: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CartRecipeLineSyncMaxAggregateOutputType = {
  id: string | null
  syncId: string | null
  recipeIngredientId: string | null
  syncedQuantity: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CartRecipeLineSyncCountAggregateOutputType = {
  id: number
  syncId: number
  recipeIngredientId: number
  syncedQuantity: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CartRecipeLineSyncAvgAggregateInputType = {
  syncedQuantity?: true
}

export type CartRecipeLineSyncSumAggregateInputType = {
  syncedQuantity?: true
}

export type CartRecipeLineSyncMinAggregateInputType = {
  id?: true
  syncId?: true
  recipeIngredientId?: true
  syncedQuantity?: true
  createdAt?: true
  updatedAt?: true
}

export type CartRecipeLineSyncMaxAggregateInputType = {
  id?: true
  syncId?: true
  recipeIngredientId?: true
  syncedQuantity?: true
  createdAt?: true
  updatedAt?: true
}

export type CartRecipeLineSyncCountAggregateInputType = {
  id?: true
  syncId?: true
  recipeIngredientId?: true
  syncedQuantity?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CartRecipeLineSyncAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CartRecipeLineSync to aggregate.
   */
  where?: Prisma.CartRecipeLineSyncWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CartRecipeLineSyncs to fetch.
   */
  orderBy?: Prisma.CartRecipeLineSyncOrderByWithRelationInput | Prisma.CartRecipeLineSyncOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CartRecipeLineSyncWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CartRecipeLineSyncs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CartRecipeLineSyncs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CartRecipeLineSyncs
  **/
  _count?: true | CartRecipeLineSyncCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CartRecipeLineSyncAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CartRecipeLineSyncSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CartRecipeLineSyncMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CartRecipeLineSyncMaxAggregateInputType
}

export type GetCartRecipeLineSyncAggregateType<T extends CartRecipeLineSyncAggregateArgs> = {
      [P in keyof T & keyof AggregateCartRecipeLineSync]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCartRecipeLineSync[P]>
    : Prisma.GetScalarType<T[P], AggregateCartRecipeLineSync[P]>
}




export type CartRecipeLineSyncGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CartRecipeLineSyncWhereInput
  orderBy?: Prisma.CartRecipeLineSyncOrderByWithAggregationInput | Prisma.CartRecipeLineSyncOrderByWithAggregationInput[]
  by: Prisma.CartRecipeLineSyncScalarFieldEnum[] | Prisma.CartRecipeLineSyncScalarFieldEnum
  having?: Prisma.CartRecipeLineSyncScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CartRecipeLineSyncCountAggregateInputType | true
  _avg?: CartRecipeLineSyncAvgAggregateInputType
  _sum?: CartRecipeLineSyncSumAggregateInputType
  _min?: CartRecipeLineSyncMinAggregateInputType
  _max?: CartRecipeLineSyncMaxAggregateInputType
}

export type CartRecipeLineSyncGroupByOutputType = {
  id: string
  syncId: string
  recipeIngredientId: string
  syncedQuantity: runtime.Decimal
  createdAt: Date
  updatedAt: Date
  _count: CartRecipeLineSyncCountAggregateOutputType | null
  _avg: CartRecipeLineSyncAvgAggregateOutputType | null
  _sum: CartRecipeLineSyncSumAggregateOutputType | null
  _min: CartRecipeLineSyncMinAggregateOutputType | null
  _max: CartRecipeLineSyncMaxAggregateOutputType | null
}

export type GetCartRecipeLineSyncGroupByPayload<T extends CartRecipeLineSyncGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CartRecipeLineSyncGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CartRecipeLineSyncGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CartRecipeLineSyncGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CartRecipeLineSyncGroupByOutputType[P]>
      }
    >
  >



export type CartRecipeLineSyncWhereInput = {
  AND?: Prisma.CartRecipeLineSyncWhereInput | Prisma.CartRecipeLineSyncWhereInput[]
  OR?: Prisma.CartRecipeLineSyncWhereInput[]
  NOT?: Prisma.CartRecipeLineSyncWhereInput | Prisma.CartRecipeLineSyncWhereInput[]
  id?: Prisma.StringFilter<"CartRecipeLineSync"> | string
  syncId?: Prisma.StringFilter<"CartRecipeLineSync"> | string
  recipeIngredientId?: Prisma.StringFilter<"CartRecipeLineSync"> | string
  syncedQuantity?: Prisma.DecimalFilter<"CartRecipeLineSync"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"CartRecipeLineSync"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CartRecipeLineSync"> | Date | string
  sync?: Prisma.XOR<Prisma.CartRecipeSyncScalarRelationFilter, Prisma.CartRecipeSyncWhereInput>
}

export type CartRecipeLineSyncOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  syncId?: Prisma.SortOrder
  recipeIngredientId?: Prisma.SortOrder
  syncedQuantity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  sync?: Prisma.CartRecipeSyncOrderByWithRelationInput
}

export type CartRecipeLineSyncWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  syncId_recipeIngredientId?: Prisma.CartRecipeLineSyncSyncIdRecipeIngredientIdCompoundUniqueInput
  AND?: Prisma.CartRecipeLineSyncWhereInput | Prisma.CartRecipeLineSyncWhereInput[]
  OR?: Prisma.CartRecipeLineSyncWhereInput[]
  NOT?: Prisma.CartRecipeLineSyncWhereInput | Prisma.CartRecipeLineSyncWhereInput[]
  syncId?: Prisma.StringFilter<"CartRecipeLineSync"> | string
  recipeIngredientId?: Prisma.StringFilter<"CartRecipeLineSync"> | string
  syncedQuantity?: Prisma.DecimalFilter<"CartRecipeLineSync"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"CartRecipeLineSync"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CartRecipeLineSync"> | Date | string
  sync?: Prisma.XOR<Prisma.CartRecipeSyncScalarRelationFilter, Prisma.CartRecipeSyncWhereInput>
}, "id" | "syncId_recipeIngredientId">

export type CartRecipeLineSyncOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  syncId?: Prisma.SortOrder
  recipeIngredientId?: Prisma.SortOrder
  syncedQuantity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CartRecipeLineSyncCountOrderByAggregateInput
  _avg?: Prisma.CartRecipeLineSyncAvgOrderByAggregateInput
  _max?: Prisma.CartRecipeLineSyncMaxOrderByAggregateInput
  _min?: Prisma.CartRecipeLineSyncMinOrderByAggregateInput
  _sum?: Prisma.CartRecipeLineSyncSumOrderByAggregateInput
}

export type CartRecipeLineSyncScalarWhereWithAggregatesInput = {
  AND?: Prisma.CartRecipeLineSyncScalarWhereWithAggregatesInput | Prisma.CartRecipeLineSyncScalarWhereWithAggregatesInput[]
  OR?: Prisma.CartRecipeLineSyncScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CartRecipeLineSyncScalarWhereWithAggregatesInput | Prisma.CartRecipeLineSyncScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CartRecipeLineSync"> | string
  syncId?: Prisma.StringWithAggregatesFilter<"CartRecipeLineSync"> | string
  recipeIngredientId?: Prisma.StringWithAggregatesFilter<"CartRecipeLineSync"> | string
  syncedQuantity?: Prisma.DecimalWithAggregatesFilter<"CartRecipeLineSync"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CartRecipeLineSync"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CartRecipeLineSync"> | Date | string
}

export type CartRecipeLineSyncCreateInput = {
  id?: string
  recipeIngredientId: string
  syncedQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  sync: Prisma.CartRecipeSyncCreateNestedOneWithoutLineSyncsInput
}

export type CartRecipeLineSyncUncheckedCreateInput = {
  id?: string
  syncId: string
  recipeIngredientId: string
  syncedQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CartRecipeLineSyncUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipeIngredientId?: Prisma.StringFieldUpdateOperationsInput | string
  syncedQuantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sync?: Prisma.CartRecipeSyncUpdateOneRequiredWithoutLineSyncsNestedInput
}

export type CartRecipeLineSyncUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  syncId?: Prisma.StringFieldUpdateOperationsInput | string
  recipeIngredientId?: Prisma.StringFieldUpdateOperationsInput | string
  syncedQuantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CartRecipeLineSyncCreateManyInput = {
  id?: string
  syncId: string
  recipeIngredientId: string
  syncedQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CartRecipeLineSyncUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipeIngredientId?: Prisma.StringFieldUpdateOperationsInput | string
  syncedQuantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CartRecipeLineSyncUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  syncId?: Prisma.StringFieldUpdateOperationsInput | string
  recipeIngredientId?: Prisma.StringFieldUpdateOperationsInput | string
  syncedQuantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CartRecipeLineSyncListRelationFilter = {
  every?: Prisma.CartRecipeLineSyncWhereInput
  some?: Prisma.CartRecipeLineSyncWhereInput
  none?: Prisma.CartRecipeLineSyncWhereInput
}

export type CartRecipeLineSyncOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CartRecipeLineSyncSyncIdRecipeIngredientIdCompoundUniqueInput = {
  syncId: string
  recipeIngredientId: string
}

export type CartRecipeLineSyncCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  syncId?: Prisma.SortOrder
  recipeIngredientId?: Prisma.SortOrder
  syncedQuantity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CartRecipeLineSyncAvgOrderByAggregateInput = {
  syncedQuantity?: Prisma.SortOrder
}

export type CartRecipeLineSyncMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  syncId?: Prisma.SortOrder
  recipeIngredientId?: Prisma.SortOrder
  syncedQuantity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CartRecipeLineSyncMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  syncId?: Prisma.SortOrder
  recipeIngredientId?: Prisma.SortOrder
  syncedQuantity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CartRecipeLineSyncSumOrderByAggregateInput = {
  syncedQuantity?: Prisma.SortOrder
}

export type CartRecipeLineSyncCreateNestedManyWithoutSyncInput = {
  create?: Prisma.XOR<Prisma.CartRecipeLineSyncCreateWithoutSyncInput, Prisma.CartRecipeLineSyncUncheckedCreateWithoutSyncInput> | Prisma.CartRecipeLineSyncCreateWithoutSyncInput[] | Prisma.CartRecipeLineSyncUncheckedCreateWithoutSyncInput[]
  connectOrCreate?: Prisma.CartRecipeLineSyncCreateOrConnectWithoutSyncInput | Prisma.CartRecipeLineSyncCreateOrConnectWithoutSyncInput[]
  createMany?: Prisma.CartRecipeLineSyncCreateManySyncInputEnvelope
  connect?: Prisma.CartRecipeLineSyncWhereUniqueInput | Prisma.CartRecipeLineSyncWhereUniqueInput[]
}

export type CartRecipeLineSyncUncheckedCreateNestedManyWithoutSyncInput = {
  create?: Prisma.XOR<Prisma.CartRecipeLineSyncCreateWithoutSyncInput, Prisma.CartRecipeLineSyncUncheckedCreateWithoutSyncInput> | Prisma.CartRecipeLineSyncCreateWithoutSyncInput[] | Prisma.CartRecipeLineSyncUncheckedCreateWithoutSyncInput[]
  connectOrCreate?: Prisma.CartRecipeLineSyncCreateOrConnectWithoutSyncInput | Prisma.CartRecipeLineSyncCreateOrConnectWithoutSyncInput[]
  createMany?: Prisma.CartRecipeLineSyncCreateManySyncInputEnvelope
  connect?: Prisma.CartRecipeLineSyncWhereUniqueInput | Prisma.CartRecipeLineSyncWhereUniqueInput[]
}

export type CartRecipeLineSyncUpdateManyWithoutSyncNestedInput = {
  create?: Prisma.XOR<Prisma.CartRecipeLineSyncCreateWithoutSyncInput, Prisma.CartRecipeLineSyncUncheckedCreateWithoutSyncInput> | Prisma.CartRecipeLineSyncCreateWithoutSyncInput[] | Prisma.CartRecipeLineSyncUncheckedCreateWithoutSyncInput[]
  connectOrCreate?: Prisma.CartRecipeLineSyncCreateOrConnectWithoutSyncInput | Prisma.CartRecipeLineSyncCreateOrConnectWithoutSyncInput[]
  upsert?: Prisma.CartRecipeLineSyncUpsertWithWhereUniqueWithoutSyncInput | Prisma.CartRecipeLineSyncUpsertWithWhereUniqueWithoutSyncInput[]
  createMany?: Prisma.CartRecipeLineSyncCreateManySyncInputEnvelope
  set?: Prisma.CartRecipeLineSyncWhereUniqueInput | Prisma.CartRecipeLineSyncWhereUniqueInput[]
  disconnect?: Prisma.CartRecipeLineSyncWhereUniqueInput | Prisma.CartRecipeLineSyncWhereUniqueInput[]
  delete?: Prisma.CartRecipeLineSyncWhereUniqueInput | Prisma.CartRecipeLineSyncWhereUniqueInput[]
  connect?: Prisma.CartRecipeLineSyncWhereUniqueInput | Prisma.CartRecipeLineSyncWhereUniqueInput[]
  update?: Prisma.CartRecipeLineSyncUpdateWithWhereUniqueWithoutSyncInput | Prisma.CartRecipeLineSyncUpdateWithWhereUniqueWithoutSyncInput[]
  updateMany?: Prisma.CartRecipeLineSyncUpdateManyWithWhereWithoutSyncInput | Prisma.CartRecipeLineSyncUpdateManyWithWhereWithoutSyncInput[]
  deleteMany?: Prisma.CartRecipeLineSyncScalarWhereInput | Prisma.CartRecipeLineSyncScalarWhereInput[]
}

export type CartRecipeLineSyncUncheckedUpdateManyWithoutSyncNestedInput = {
  create?: Prisma.XOR<Prisma.CartRecipeLineSyncCreateWithoutSyncInput, Prisma.CartRecipeLineSyncUncheckedCreateWithoutSyncInput> | Prisma.CartRecipeLineSyncCreateWithoutSyncInput[] | Prisma.CartRecipeLineSyncUncheckedCreateWithoutSyncInput[]
  connectOrCreate?: Prisma.CartRecipeLineSyncCreateOrConnectWithoutSyncInput | Prisma.CartRecipeLineSyncCreateOrConnectWithoutSyncInput[]
  upsert?: Prisma.CartRecipeLineSyncUpsertWithWhereUniqueWithoutSyncInput | Prisma.CartRecipeLineSyncUpsertWithWhereUniqueWithoutSyncInput[]
  createMany?: Prisma.CartRecipeLineSyncCreateManySyncInputEnvelope
  set?: Prisma.CartRecipeLineSyncWhereUniqueInput | Prisma.CartRecipeLineSyncWhereUniqueInput[]
  disconnect?: Prisma.CartRecipeLineSyncWhereUniqueInput | Prisma.CartRecipeLineSyncWhereUniqueInput[]
  delete?: Prisma.CartRecipeLineSyncWhereUniqueInput | Prisma.CartRecipeLineSyncWhereUniqueInput[]
  connect?: Prisma.CartRecipeLineSyncWhereUniqueInput | Prisma.CartRecipeLineSyncWhereUniqueInput[]
  update?: Prisma.CartRecipeLineSyncUpdateWithWhereUniqueWithoutSyncInput | Prisma.CartRecipeLineSyncUpdateWithWhereUniqueWithoutSyncInput[]
  updateMany?: Prisma.CartRecipeLineSyncUpdateManyWithWhereWithoutSyncInput | Prisma.CartRecipeLineSyncUpdateManyWithWhereWithoutSyncInput[]
  deleteMany?: Prisma.CartRecipeLineSyncScalarWhereInput | Prisma.CartRecipeLineSyncScalarWhereInput[]
}

export type CartRecipeLineSyncCreateWithoutSyncInput = {
  id?: string
  recipeIngredientId: string
  syncedQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CartRecipeLineSyncUncheckedCreateWithoutSyncInput = {
  id?: string
  recipeIngredientId: string
  syncedQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CartRecipeLineSyncCreateOrConnectWithoutSyncInput = {
  where: Prisma.CartRecipeLineSyncWhereUniqueInput
  create: Prisma.XOR<Prisma.CartRecipeLineSyncCreateWithoutSyncInput, Prisma.CartRecipeLineSyncUncheckedCreateWithoutSyncInput>
}

export type CartRecipeLineSyncCreateManySyncInputEnvelope = {
  data: Prisma.CartRecipeLineSyncCreateManySyncInput | Prisma.CartRecipeLineSyncCreateManySyncInput[]
  skipDuplicates?: boolean
}

export type CartRecipeLineSyncUpsertWithWhereUniqueWithoutSyncInput = {
  where: Prisma.CartRecipeLineSyncWhereUniqueInput
  update: Prisma.XOR<Prisma.CartRecipeLineSyncUpdateWithoutSyncInput, Prisma.CartRecipeLineSyncUncheckedUpdateWithoutSyncInput>
  create: Prisma.XOR<Prisma.CartRecipeLineSyncCreateWithoutSyncInput, Prisma.CartRecipeLineSyncUncheckedCreateWithoutSyncInput>
}

export type CartRecipeLineSyncUpdateWithWhereUniqueWithoutSyncInput = {
  where: Prisma.CartRecipeLineSyncWhereUniqueInput
  data: Prisma.XOR<Prisma.CartRecipeLineSyncUpdateWithoutSyncInput, Prisma.CartRecipeLineSyncUncheckedUpdateWithoutSyncInput>
}

export type CartRecipeLineSyncUpdateManyWithWhereWithoutSyncInput = {
  where: Prisma.CartRecipeLineSyncScalarWhereInput
  data: Prisma.XOR<Prisma.CartRecipeLineSyncUpdateManyMutationInput, Prisma.CartRecipeLineSyncUncheckedUpdateManyWithoutSyncInput>
}

export type CartRecipeLineSyncScalarWhereInput = {
  AND?: Prisma.CartRecipeLineSyncScalarWhereInput | Prisma.CartRecipeLineSyncScalarWhereInput[]
  OR?: Prisma.CartRecipeLineSyncScalarWhereInput[]
  NOT?: Prisma.CartRecipeLineSyncScalarWhereInput | Prisma.CartRecipeLineSyncScalarWhereInput[]
  id?: Prisma.StringFilter<"CartRecipeLineSync"> | string
  syncId?: Prisma.StringFilter<"CartRecipeLineSync"> | string
  recipeIngredientId?: Prisma.StringFilter<"CartRecipeLineSync"> | string
  syncedQuantity?: Prisma.DecimalFilter<"CartRecipeLineSync"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"CartRecipeLineSync"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CartRecipeLineSync"> | Date | string
}

export type CartRecipeLineSyncCreateManySyncInput = {
  id?: string
  recipeIngredientId: string
  syncedQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CartRecipeLineSyncUpdateWithoutSyncInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipeIngredientId?: Prisma.StringFieldUpdateOperationsInput | string
  syncedQuantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CartRecipeLineSyncUncheckedUpdateWithoutSyncInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipeIngredientId?: Prisma.StringFieldUpdateOperationsInput | string
  syncedQuantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CartRecipeLineSyncUncheckedUpdateManyWithoutSyncInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipeIngredientId?: Prisma.StringFieldUpdateOperationsInput | string
  syncedQuantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CartRecipeLineSyncSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  syncId?: boolean
  recipeIngredientId?: boolean
  syncedQuantity?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sync?: boolean | Prisma.CartRecipeSyncDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cartRecipeLineSync"]>

export type CartRecipeLineSyncSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  syncId?: boolean
  recipeIngredientId?: boolean
  syncedQuantity?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sync?: boolean | Prisma.CartRecipeSyncDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cartRecipeLineSync"]>

export type CartRecipeLineSyncSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  syncId?: boolean
  recipeIngredientId?: boolean
  syncedQuantity?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sync?: boolean | Prisma.CartRecipeSyncDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cartRecipeLineSync"]>

export type CartRecipeLineSyncSelectScalar = {
  id?: boolean
  syncId?: boolean
  recipeIngredientId?: boolean
  syncedQuantity?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CartRecipeLineSyncOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "syncId" | "recipeIngredientId" | "syncedQuantity" | "createdAt" | "updatedAt", ExtArgs["result"]["cartRecipeLineSync"]>
export type CartRecipeLineSyncInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sync?: boolean | Prisma.CartRecipeSyncDefaultArgs<ExtArgs>
}
export type CartRecipeLineSyncIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sync?: boolean | Prisma.CartRecipeSyncDefaultArgs<ExtArgs>
}
export type CartRecipeLineSyncIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sync?: boolean | Prisma.CartRecipeSyncDefaultArgs<ExtArgs>
}

export type $CartRecipeLineSyncPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CartRecipeLineSync"
  objects: {
    sync: Prisma.$CartRecipeSyncPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    syncId: string
    recipeIngredientId: string
    syncedQuantity: runtime.Decimal
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["cartRecipeLineSync"]>
  composites: {}
}

export type CartRecipeLineSyncGetPayload<S extends boolean | null | undefined | CartRecipeLineSyncDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CartRecipeLineSyncPayload, S>

export type CartRecipeLineSyncCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CartRecipeLineSyncFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CartRecipeLineSyncCountAggregateInputType | true
  }

export interface CartRecipeLineSyncDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CartRecipeLineSync'], meta: { name: 'CartRecipeLineSync' } }
  /**
   * Find zero or one CartRecipeLineSync that matches the filter.
   * @param {CartRecipeLineSyncFindUniqueArgs} args - Arguments to find a CartRecipeLineSync
   * @example
   * // Get one CartRecipeLineSync
   * const cartRecipeLineSync = await prisma.cartRecipeLineSync.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CartRecipeLineSyncFindUniqueArgs>(args: Prisma.SelectSubset<T, CartRecipeLineSyncFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CartRecipeLineSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeLineSyncPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CartRecipeLineSync that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CartRecipeLineSyncFindUniqueOrThrowArgs} args - Arguments to find a CartRecipeLineSync
   * @example
   * // Get one CartRecipeLineSync
   * const cartRecipeLineSync = await prisma.cartRecipeLineSync.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CartRecipeLineSyncFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CartRecipeLineSyncFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CartRecipeLineSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeLineSyncPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CartRecipeLineSync that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartRecipeLineSyncFindFirstArgs} args - Arguments to find a CartRecipeLineSync
   * @example
   * // Get one CartRecipeLineSync
   * const cartRecipeLineSync = await prisma.cartRecipeLineSync.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CartRecipeLineSyncFindFirstArgs>(args?: Prisma.SelectSubset<T, CartRecipeLineSyncFindFirstArgs<ExtArgs>>): Prisma.Prisma__CartRecipeLineSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeLineSyncPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CartRecipeLineSync that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartRecipeLineSyncFindFirstOrThrowArgs} args - Arguments to find a CartRecipeLineSync
   * @example
   * // Get one CartRecipeLineSync
   * const cartRecipeLineSync = await prisma.cartRecipeLineSync.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CartRecipeLineSyncFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CartRecipeLineSyncFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CartRecipeLineSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeLineSyncPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CartRecipeLineSyncs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartRecipeLineSyncFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CartRecipeLineSyncs
   * const cartRecipeLineSyncs = await prisma.cartRecipeLineSync.findMany()
   * 
   * // Get first 10 CartRecipeLineSyncs
   * const cartRecipeLineSyncs = await prisma.cartRecipeLineSync.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const cartRecipeLineSyncWithIdOnly = await prisma.cartRecipeLineSync.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CartRecipeLineSyncFindManyArgs>(args?: Prisma.SelectSubset<T, CartRecipeLineSyncFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CartRecipeLineSyncPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CartRecipeLineSync.
   * @param {CartRecipeLineSyncCreateArgs} args - Arguments to create a CartRecipeLineSync.
   * @example
   * // Create one CartRecipeLineSync
   * const CartRecipeLineSync = await prisma.cartRecipeLineSync.create({
   *   data: {
   *     // ... data to create a CartRecipeLineSync
   *   }
   * })
   * 
   */
  create<T extends CartRecipeLineSyncCreateArgs>(args: Prisma.SelectSubset<T, CartRecipeLineSyncCreateArgs<ExtArgs>>): Prisma.Prisma__CartRecipeLineSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeLineSyncPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CartRecipeLineSyncs.
   * @param {CartRecipeLineSyncCreateManyArgs} args - Arguments to create many CartRecipeLineSyncs.
   * @example
   * // Create many CartRecipeLineSyncs
   * const cartRecipeLineSync = await prisma.cartRecipeLineSync.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CartRecipeLineSyncCreateManyArgs>(args?: Prisma.SelectSubset<T, CartRecipeLineSyncCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CartRecipeLineSyncs and returns the data saved in the database.
   * @param {CartRecipeLineSyncCreateManyAndReturnArgs} args - Arguments to create many CartRecipeLineSyncs.
   * @example
   * // Create many CartRecipeLineSyncs
   * const cartRecipeLineSync = await prisma.cartRecipeLineSync.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CartRecipeLineSyncs and only return the `id`
   * const cartRecipeLineSyncWithIdOnly = await prisma.cartRecipeLineSync.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CartRecipeLineSyncCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CartRecipeLineSyncCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CartRecipeLineSyncPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CartRecipeLineSync.
   * @param {CartRecipeLineSyncDeleteArgs} args - Arguments to delete one CartRecipeLineSync.
   * @example
   * // Delete one CartRecipeLineSync
   * const CartRecipeLineSync = await prisma.cartRecipeLineSync.delete({
   *   where: {
   *     // ... filter to delete one CartRecipeLineSync
   *   }
   * })
   * 
   */
  delete<T extends CartRecipeLineSyncDeleteArgs>(args: Prisma.SelectSubset<T, CartRecipeLineSyncDeleteArgs<ExtArgs>>): Prisma.Prisma__CartRecipeLineSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeLineSyncPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CartRecipeLineSync.
   * @param {CartRecipeLineSyncUpdateArgs} args - Arguments to update one CartRecipeLineSync.
   * @example
   * // Update one CartRecipeLineSync
   * const cartRecipeLineSync = await prisma.cartRecipeLineSync.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CartRecipeLineSyncUpdateArgs>(args: Prisma.SelectSubset<T, CartRecipeLineSyncUpdateArgs<ExtArgs>>): Prisma.Prisma__CartRecipeLineSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeLineSyncPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CartRecipeLineSyncs.
   * @param {CartRecipeLineSyncDeleteManyArgs} args - Arguments to filter CartRecipeLineSyncs to delete.
   * @example
   * // Delete a few CartRecipeLineSyncs
   * const { count } = await prisma.cartRecipeLineSync.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CartRecipeLineSyncDeleteManyArgs>(args?: Prisma.SelectSubset<T, CartRecipeLineSyncDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CartRecipeLineSyncs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartRecipeLineSyncUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CartRecipeLineSyncs
   * const cartRecipeLineSync = await prisma.cartRecipeLineSync.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CartRecipeLineSyncUpdateManyArgs>(args: Prisma.SelectSubset<T, CartRecipeLineSyncUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CartRecipeLineSyncs and returns the data updated in the database.
   * @param {CartRecipeLineSyncUpdateManyAndReturnArgs} args - Arguments to update many CartRecipeLineSyncs.
   * @example
   * // Update many CartRecipeLineSyncs
   * const cartRecipeLineSync = await prisma.cartRecipeLineSync.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CartRecipeLineSyncs and only return the `id`
   * const cartRecipeLineSyncWithIdOnly = await prisma.cartRecipeLineSync.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CartRecipeLineSyncUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CartRecipeLineSyncUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CartRecipeLineSyncPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CartRecipeLineSync.
   * @param {CartRecipeLineSyncUpsertArgs} args - Arguments to update or create a CartRecipeLineSync.
   * @example
   * // Update or create a CartRecipeLineSync
   * const cartRecipeLineSync = await prisma.cartRecipeLineSync.upsert({
   *   create: {
   *     // ... data to create a CartRecipeLineSync
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CartRecipeLineSync we want to update
   *   }
   * })
   */
  upsert<T extends CartRecipeLineSyncUpsertArgs>(args: Prisma.SelectSubset<T, CartRecipeLineSyncUpsertArgs<ExtArgs>>): Prisma.Prisma__CartRecipeLineSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeLineSyncPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CartRecipeLineSyncs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartRecipeLineSyncCountArgs} args - Arguments to filter CartRecipeLineSyncs to count.
   * @example
   * // Count the number of CartRecipeLineSyncs
   * const count = await prisma.cartRecipeLineSync.count({
   *   where: {
   *     // ... the filter for the CartRecipeLineSyncs we want to count
   *   }
   * })
  **/
  count<T extends CartRecipeLineSyncCountArgs>(
    args?: Prisma.Subset<T, CartRecipeLineSyncCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CartRecipeLineSyncCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CartRecipeLineSync.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartRecipeLineSyncAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CartRecipeLineSyncAggregateArgs>(args: Prisma.Subset<T, CartRecipeLineSyncAggregateArgs>): Prisma.PrismaPromise<GetCartRecipeLineSyncAggregateType<T>>

  /**
   * Group by CartRecipeLineSync.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartRecipeLineSyncGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CartRecipeLineSyncGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CartRecipeLineSyncGroupByArgs['orderBy'] }
      : { orderBy?: CartRecipeLineSyncGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CartRecipeLineSyncGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCartRecipeLineSyncGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CartRecipeLineSync model
 */
readonly fields: CartRecipeLineSyncFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CartRecipeLineSync.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CartRecipeLineSyncClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  sync<T extends Prisma.CartRecipeSyncDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CartRecipeSyncDefaultArgs<ExtArgs>>): Prisma.Prisma__CartRecipeSyncClient<runtime.Types.Result.GetResult<Prisma.$CartRecipeSyncPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CartRecipeLineSync model
 */
export interface CartRecipeLineSyncFieldRefs {
  readonly id: Prisma.FieldRef<"CartRecipeLineSync", 'String'>
  readonly syncId: Prisma.FieldRef<"CartRecipeLineSync", 'String'>
  readonly recipeIngredientId: Prisma.FieldRef<"CartRecipeLineSync", 'String'>
  readonly syncedQuantity: Prisma.FieldRef<"CartRecipeLineSync", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"CartRecipeLineSync", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CartRecipeLineSync", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CartRecipeLineSync findUnique
 */
export type CartRecipeLineSyncFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeLineSync
   */
  select?: Prisma.CartRecipeLineSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeLineSync
   */
  omit?: Prisma.CartRecipeLineSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeLineSyncInclude<ExtArgs> | null
  /**
   * Filter, which CartRecipeLineSync to fetch.
   */
  where: Prisma.CartRecipeLineSyncWhereUniqueInput
}

/**
 * CartRecipeLineSync findUniqueOrThrow
 */
export type CartRecipeLineSyncFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeLineSync
   */
  select?: Prisma.CartRecipeLineSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeLineSync
   */
  omit?: Prisma.CartRecipeLineSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeLineSyncInclude<ExtArgs> | null
  /**
   * Filter, which CartRecipeLineSync to fetch.
   */
  where: Prisma.CartRecipeLineSyncWhereUniqueInput
}

/**
 * CartRecipeLineSync findFirst
 */
export type CartRecipeLineSyncFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeLineSync
   */
  select?: Prisma.CartRecipeLineSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeLineSync
   */
  omit?: Prisma.CartRecipeLineSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeLineSyncInclude<ExtArgs> | null
  /**
   * Filter, which CartRecipeLineSync to fetch.
   */
  where?: Prisma.CartRecipeLineSyncWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CartRecipeLineSyncs to fetch.
   */
  orderBy?: Prisma.CartRecipeLineSyncOrderByWithRelationInput | Prisma.CartRecipeLineSyncOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CartRecipeLineSyncs.
   */
  cursor?: Prisma.CartRecipeLineSyncWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CartRecipeLineSyncs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CartRecipeLineSyncs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CartRecipeLineSyncs.
   */
  distinct?: Prisma.CartRecipeLineSyncScalarFieldEnum | Prisma.CartRecipeLineSyncScalarFieldEnum[]
}

/**
 * CartRecipeLineSync findFirstOrThrow
 */
export type CartRecipeLineSyncFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeLineSync
   */
  select?: Prisma.CartRecipeLineSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeLineSync
   */
  omit?: Prisma.CartRecipeLineSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeLineSyncInclude<ExtArgs> | null
  /**
   * Filter, which CartRecipeLineSync to fetch.
   */
  where?: Prisma.CartRecipeLineSyncWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CartRecipeLineSyncs to fetch.
   */
  orderBy?: Prisma.CartRecipeLineSyncOrderByWithRelationInput | Prisma.CartRecipeLineSyncOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CartRecipeLineSyncs.
   */
  cursor?: Prisma.CartRecipeLineSyncWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CartRecipeLineSyncs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CartRecipeLineSyncs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CartRecipeLineSyncs.
   */
  distinct?: Prisma.CartRecipeLineSyncScalarFieldEnum | Prisma.CartRecipeLineSyncScalarFieldEnum[]
}

/**
 * CartRecipeLineSync findMany
 */
export type CartRecipeLineSyncFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeLineSync
   */
  select?: Prisma.CartRecipeLineSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeLineSync
   */
  omit?: Prisma.CartRecipeLineSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeLineSyncInclude<ExtArgs> | null
  /**
   * Filter, which CartRecipeLineSyncs to fetch.
   */
  where?: Prisma.CartRecipeLineSyncWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CartRecipeLineSyncs to fetch.
   */
  orderBy?: Prisma.CartRecipeLineSyncOrderByWithRelationInput | Prisma.CartRecipeLineSyncOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CartRecipeLineSyncs.
   */
  cursor?: Prisma.CartRecipeLineSyncWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CartRecipeLineSyncs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CartRecipeLineSyncs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CartRecipeLineSyncs.
   */
  distinct?: Prisma.CartRecipeLineSyncScalarFieldEnum | Prisma.CartRecipeLineSyncScalarFieldEnum[]
}

/**
 * CartRecipeLineSync create
 */
export type CartRecipeLineSyncCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeLineSync
   */
  select?: Prisma.CartRecipeLineSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeLineSync
   */
  omit?: Prisma.CartRecipeLineSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeLineSyncInclude<ExtArgs> | null
  /**
   * The data needed to create a CartRecipeLineSync.
   */
  data: Prisma.XOR<Prisma.CartRecipeLineSyncCreateInput, Prisma.CartRecipeLineSyncUncheckedCreateInput>
}

/**
 * CartRecipeLineSync createMany
 */
export type CartRecipeLineSyncCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CartRecipeLineSyncs.
   */
  data: Prisma.CartRecipeLineSyncCreateManyInput | Prisma.CartRecipeLineSyncCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CartRecipeLineSync createManyAndReturn
 */
export type CartRecipeLineSyncCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeLineSync
   */
  select?: Prisma.CartRecipeLineSyncSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeLineSync
   */
  omit?: Prisma.CartRecipeLineSyncOmit<ExtArgs> | null
  /**
   * The data used to create many CartRecipeLineSyncs.
   */
  data: Prisma.CartRecipeLineSyncCreateManyInput | Prisma.CartRecipeLineSyncCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeLineSyncIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CartRecipeLineSync update
 */
export type CartRecipeLineSyncUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeLineSync
   */
  select?: Prisma.CartRecipeLineSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeLineSync
   */
  omit?: Prisma.CartRecipeLineSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeLineSyncInclude<ExtArgs> | null
  /**
   * The data needed to update a CartRecipeLineSync.
   */
  data: Prisma.XOR<Prisma.CartRecipeLineSyncUpdateInput, Prisma.CartRecipeLineSyncUncheckedUpdateInput>
  /**
   * Choose, which CartRecipeLineSync to update.
   */
  where: Prisma.CartRecipeLineSyncWhereUniqueInput
}

/**
 * CartRecipeLineSync updateMany
 */
export type CartRecipeLineSyncUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CartRecipeLineSyncs.
   */
  data: Prisma.XOR<Prisma.CartRecipeLineSyncUpdateManyMutationInput, Prisma.CartRecipeLineSyncUncheckedUpdateManyInput>
  /**
   * Filter which CartRecipeLineSyncs to update
   */
  where?: Prisma.CartRecipeLineSyncWhereInput
  /**
   * Limit how many CartRecipeLineSyncs to update.
   */
  limit?: number
}

/**
 * CartRecipeLineSync updateManyAndReturn
 */
export type CartRecipeLineSyncUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeLineSync
   */
  select?: Prisma.CartRecipeLineSyncSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeLineSync
   */
  omit?: Prisma.CartRecipeLineSyncOmit<ExtArgs> | null
  /**
   * The data used to update CartRecipeLineSyncs.
   */
  data: Prisma.XOR<Prisma.CartRecipeLineSyncUpdateManyMutationInput, Prisma.CartRecipeLineSyncUncheckedUpdateManyInput>
  /**
   * Filter which CartRecipeLineSyncs to update
   */
  where?: Prisma.CartRecipeLineSyncWhereInput
  /**
   * Limit how many CartRecipeLineSyncs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeLineSyncIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CartRecipeLineSync upsert
 */
export type CartRecipeLineSyncUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeLineSync
   */
  select?: Prisma.CartRecipeLineSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeLineSync
   */
  omit?: Prisma.CartRecipeLineSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeLineSyncInclude<ExtArgs> | null
  /**
   * The filter to search for the CartRecipeLineSync to update in case it exists.
   */
  where: Prisma.CartRecipeLineSyncWhereUniqueInput
  /**
   * In case the CartRecipeLineSync found by the `where` argument doesn't exist, create a new CartRecipeLineSync with this data.
   */
  create: Prisma.XOR<Prisma.CartRecipeLineSyncCreateInput, Prisma.CartRecipeLineSyncUncheckedCreateInput>
  /**
   * In case the CartRecipeLineSync was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CartRecipeLineSyncUpdateInput, Prisma.CartRecipeLineSyncUncheckedUpdateInput>
}

/**
 * CartRecipeLineSync delete
 */
export type CartRecipeLineSyncDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeLineSync
   */
  select?: Prisma.CartRecipeLineSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeLineSync
   */
  omit?: Prisma.CartRecipeLineSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeLineSyncInclude<ExtArgs> | null
  /**
   * Filter which CartRecipeLineSync to delete.
   */
  where: Prisma.CartRecipeLineSyncWhereUniqueInput
}

/**
 * CartRecipeLineSync deleteMany
 */
export type CartRecipeLineSyncDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CartRecipeLineSyncs to delete
   */
  where?: Prisma.CartRecipeLineSyncWhereInput
  /**
   * Limit how many CartRecipeLineSyncs to delete.
   */
  limit?: number
}

/**
 * CartRecipeLineSync without action
 */
export type CartRecipeLineSyncDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartRecipeLineSync
   */
  select?: Prisma.CartRecipeLineSyncSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartRecipeLineSync
   */
  omit?: Prisma.CartRecipeLineSyncOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartRecipeLineSyncInclude<ExtArgs> | null
}
