
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MeasurementUnit` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MeasurementUnit
 * 
 */
export type MeasurementUnitModel = runtime.Types.Result.DefaultSelection<Prisma.$MeasurementUnitPayload>

export type AggregateMeasurementUnit = {
  _count: MeasurementUnitCountAggregateOutputType | null
  _min: MeasurementUnitMinAggregateOutputType | null
  _max: MeasurementUnitMaxAggregateOutputType | null
}

export type MeasurementUnitMinAggregateOutputType = {
  id: string | null
  name: string | null
  shortName: string | null
  kind: $Enums.MeasurementUnitKind | null
  roundToInteger: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MeasurementUnitMaxAggregateOutputType = {
  id: string | null
  name: string | null
  shortName: string | null
  kind: $Enums.MeasurementUnitKind | null
  roundToInteger: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MeasurementUnitCountAggregateOutputType = {
  id: number
  name: number
  shortName: number
  kind: number
  roundToInteger: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MeasurementUnitMinAggregateInputType = {
  id?: true
  name?: true
  shortName?: true
  kind?: true
  roundToInteger?: true
  createdAt?: true
  updatedAt?: true
}

export type MeasurementUnitMaxAggregateInputType = {
  id?: true
  name?: true
  shortName?: true
  kind?: true
  roundToInteger?: true
  createdAt?: true
  updatedAt?: true
}

export type MeasurementUnitCountAggregateInputType = {
  id?: true
  name?: true
  shortName?: true
  kind?: true
  roundToInteger?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MeasurementUnitAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MeasurementUnit to aggregate.
   */
  where?: Prisma.MeasurementUnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MeasurementUnits to fetch.
   */
  orderBy?: Prisma.MeasurementUnitOrderByWithRelationInput | Prisma.MeasurementUnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MeasurementUnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MeasurementUnits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MeasurementUnits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MeasurementUnits
  **/
  _count?: true | MeasurementUnitCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MeasurementUnitMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MeasurementUnitMaxAggregateInputType
}

export type GetMeasurementUnitAggregateType<T extends MeasurementUnitAggregateArgs> = {
      [P in keyof T & keyof AggregateMeasurementUnit]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMeasurementUnit[P]>
    : Prisma.GetScalarType<T[P], AggregateMeasurementUnit[P]>
}




export type MeasurementUnitGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MeasurementUnitWhereInput
  orderBy?: Prisma.MeasurementUnitOrderByWithAggregationInput | Prisma.MeasurementUnitOrderByWithAggregationInput[]
  by: Prisma.MeasurementUnitScalarFieldEnum[] | Prisma.MeasurementUnitScalarFieldEnum
  having?: Prisma.MeasurementUnitScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MeasurementUnitCountAggregateInputType | true
  _min?: MeasurementUnitMinAggregateInputType
  _max?: MeasurementUnitMaxAggregateInputType
}

export type MeasurementUnitGroupByOutputType = {
  id: string
  name: string
  shortName: string
  kind: $Enums.MeasurementUnitKind
  roundToInteger: boolean
  createdAt: Date
  updatedAt: Date
  _count: MeasurementUnitCountAggregateOutputType | null
  _min: MeasurementUnitMinAggregateOutputType | null
  _max: MeasurementUnitMaxAggregateOutputType | null
}

export type GetMeasurementUnitGroupByPayload<T extends MeasurementUnitGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MeasurementUnitGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MeasurementUnitGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MeasurementUnitGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MeasurementUnitGroupByOutputType[P]>
      }
    >
  >



export type MeasurementUnitWhereInput = {
  AND?: Prisma.MeasurementUnitWhereInput | Prisma.MeasurementUnitWhereInput[]
  OR?: Prisma.MeasurementUnitWhereInput[]
  NOT?: Prisma.MeasurementUnitWhereInput | Prisma.MeasurementUnitWhereInput[]
  id?: Prisma.StringFilter<"MeasurementUnit"> | string
  name?: Prisma.StringFilter<"MeasurementUnit"> | string
  shortName?: Prisma.StringFilter<"MeasurementUnit"> | string
  kind?: Prisma.EnumMeasurementUnitKindFilter<"MeasurementUnit"> | $Enums.MeasurementUnitKind
  roundToInteger?: Prisma.BoolFilter<"MeasurementUnit"> | boolean
  createdAt?: Prisma.DateTimeFilter<"MeasurementUnit"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MeasurementUnit"> | Date | string
  ingredients?: Prisma.RecipeIngredientListRelationFilter
  recipeOutputs?: Prisma.RecipeListRelationFilter
  ingredientGroupOutputs?: Prisma.RecipeIngredientGroupListRelationFilter
}

export type MeasurementUnitOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  shortName?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  roundToInteger?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  ingredients?: Prisma.RecipeIngredientOrderByRelationAggregateInput
  recipeOutputs?: Prisma.RecipeOrderByRelationAggregateInput
  ingredientGroupOutputs?: Prisma.RecipeIngredientGroupOrderByRelationAggregateInput
}

export type MeasurementUnitWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  shortName?: string
  AND?: Prisma.MeasurementUnitWhereInput | Prisma.MeasurementUnitWhereInput[]
  OR?: Prisma.MeasurementUnitWhereInput[]
  NOT?: Prisma.MeasurementUnitWhereInput | Prisma.MeasurementUnitWhereInput[]
  name?: Prisma.StringFilter<"MeasurementUnit"> | string
  kind?: Prisma.EnumMeasurementUnitKindFilter<"MeasurementUnit"> | $Enums.MeasurementUnitKind
  roundToInteger?: Prisma.BoolFilter<"MeasurementUnit"> | boolean
  createdAt?: Prisma.DateTimeFilter<"MeasurementUnit"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MeasurementUnit"> | Date | string
  ingredients?: Prisma.RecipeIngredientListRelationFilter
  recipeOutputs?: Prisma.RecipeListRelationFilter
  ingredientGroupOutputs?: Prisma.RecipeIngredientGroupListRelationFilter
}, "id" | "shortName">

export type MeasurementUnitOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  shortName?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  roundToInteger?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MeasurementUnitCountOrderByAggregateInput
  _max?: Prisma.MeasurementUnitMaxOrderByAggregateInput
  _min?: Prisma.MeasurementUnitMinOrderByAggregateInput
}

export type MeasurementUnitScalarWhereWithAggregatesInput = {
  AND?: Prisma.MeasurementUnitScalarWhereWithAggregatesInput | Prisma.MeasurementUnitScalarWhereWithAggregatesInput[]
  OR?: Prisma.MeasurementUnitScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MeasurementUnitScalarWhereWithAggregatesInput | Prisma.MeasurementUnitScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MeasurementUnit"> | string
  name?: Prisma.StringWithAggregatesFilter<"MeasurementUnit"> | string
  shortName?: Prisma.StringWithAggregatesFilter<"MeasurementUnit"> | string
  kind?: Prisma.EnumMeasurementUnitKindWithAggregatesFilter<"MeasurementUnit"> | $Enums.MeasurementUnitKind
  roundToInteger?: Prisma.BoolWithAggregatesFilter<"MeasurementUnit"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MeasurementUnit"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MeasurementUnit"> | Date | string
}

export type MeasurementUnitCreateInput = {
  id?: string
  name: string
  shortName: string
  kind: $Enums.MeasurementUnitKind
  roundToInteger?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  ingredients?: Prisma.RecipeIngredientCreateNestedManyWithoutUnitInput
  recipeOutputs?: Prisma.RecipeCreateNestedManyWithoutOutputUnitInput
  ingredientGroupOutputs?: Prisma.RecipeIngredientGroupCreateNestedManyWithoutOutputUnitInput
}

export type MeasurementUnitUncheckedCreateInput = {
  id?: string
  name: string
  shortName: string
  kind: $Enums.MeasurementUnitKind
  roundToInteger?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  ingredients?: Prisma.RecipeIngredientUncheckedCreateNestedManyWithoutUnitInput
  recipeOutputs?: Prisma.RecipeUncheckedCreateNestedManyWithoutOutputUnitInput
  ingredientGroupOutputs?: Prisma.RecipeIngredientGroupUncheckedCreateNestedManyWithoutOutputUnitInput
}

export type MeasurementUnitUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  shortName?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumMeasurementUnitKindFieldUpdateOperationsInput | $Enums.MeasurementUnitKind
  roundToInteger?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ingredients?: Prisma.RecipeIngredientUpdateManyWithoutUnitNestedInput
  recipeOutputs?: Prisma.RecipeUpdateManyWithoutOutputUnitNestedInput
  ingredientGroupOutputs?: Prisma.RecipeIngredientGroupUpdateManyWithoutOutputUnitNestedInput
}

export type MeasurementUnitUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  shortName?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumMeasurementUnitKindFieldUpdateOperationsInput | $Enums.MeasurementUnitKind
  roundToInteger?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ingredients?: Prisma.RecipeIngredientUncheckedUpdateManyWithoutUnitNestedInput
  recipeOutputs?: Prisma.RecipeUncheckedUpdateManyWithoutOutputUnitNestedInput
  ingredientGroupOutputs?: Prisma.RecipeIngredientGroupUncheckedUpdateManyWithoutOutputUnitNestedInput
}

export type MeasurementUnitCreateManyInput = {
  id?: string
  name: string
  shortName: string
  kind: $Enums.MeasurementUnitKind
  roundToInteger?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MeasurementUnitUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  shortName?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumMeasurementUnitKindFieldUpdateOperationsInput | $Enums.MeasurementUnitKind
  roundToInteger?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MeasurementUnitUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  shortName?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumMeasurementUnitKindFieldUpdateOperationsInput | $Enums.MeasurementUnitKind
  roundToInteger?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MeasurementUnitScalarRelationFilter = {
  is?: Prisma.MeasurementUnitWhereInput
  isNot?: Prisma.MeasurementUnitWhereInput
}

export type MeasurementUnitCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  shortName?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  roundToInteger?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MeasurementUnitMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  shortName?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  roundToInteger?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MeasurementUnitMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  shortName?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  roundToInteger?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MeasurementUnitCreateNestedOneWithoutRecipeOutputsInput = {
  create?: Prisma.XOR<Prisma.MeasurementUnitCreateWithoutRecipeOutputsInput, Prisma.MeasurementUnitUncheckedCreateWithoutRecipeOutputsInput>
  connectOrCreate?: Prisma.MeasurementUnitCreateOrConnectWithoutRecipeOutputsInput
  connect?: Prisma.MeasurementUnitWhereUniqueInput
}

export type MeasurementUnitUpdateOneRequiredWithoutRecipeOutputsNestedInput = {
  create?: Prisma.XOR<Prisma.MeasurementUnitCreateWithoutRecipeOutputsInput, Prisma.MeasurementUnitUncheckedCreateWithoutRecipeOutputsInput>
  connectOrCreate?: Prisma.MeasurementUnitCreateOrConnectWithoutRecipeOutputsInput
  upsert?: Prisma.MeasurementUnitUpsertWithoutRecipeOutputsInput
  connect?: Prisma.MeasurementUnitWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MeasurementUnitUpdateToOneWithWhereWithoutRecipeOutputsInput, Prisma.MeasurementUnitUpdateWithoutRecipeOutputsInput>, Prisma.MeasurementUnitUncheckedUpdateWithoutRecipeOutputsInput>
}

export type EnumMeasurementUnitKindFieldUpdateOperationsInput = {
  set?: $Enums.MeasurementUnitKind
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type MeasurementUnitCreateNestedOneWithoutIngredientsInput = {
  create?: Prisma.XOR<Prisma.MeasurementUnitCreateWithoutIngredientsInput, Prisma.MeasurementUnitUncheckedCreateWithoutIngredientsInput>
  connectOrCreate?: Prisma.MeasurementUnitCreateOrConnectWithoutIngredientsInput
  connect?: Prisma.MeasurementUnitWhereUniqueInput
}

export type MeasurementUnitUpdateOneRequiredWithoutIngredientsNestedInput = {
  create?: Prisma.XOR<Prisma.MeasurementUnitCreateWithoutIngredientsInput, Prisma.MeasurementUnitUncheckedCreateWithoutIngredientsInput>
  connectOrCreate?: Prisma.MeasurementUnitCreateOrConnectWithoutIngredientsInput
  upsert?: Prisma.MeasurementUnitUpsertWithoutIngredientsInput
  connect?: Prisma.MeasurementUnitWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MeasurementUnitUpdateToOneWithWhereWithoutIngredientsInput, Prisma.MeasurementUnitUpdateWithoutIngredientsInput>, Prisma.MeasurementUnitUncheckedUpdateWithoutIngredientsInput>
}

export type MeasurementUnitCreateNestedOneWithoutIngredientGroupOutputsInput = {
  create?: Prisma.XOR<Prisma.MeasurementUnitCreateWithoutIngredientGroupOutputsInput, Prisma.MeasurementUnitUncheckedCreateWithoutIngredientGroupOutputsInput>
  connectOrCreate?: Prisma.MeasurementUnitCreateOrConnectWithoutIngredientGroupOutputsInput
  connect?: Prisma.MeasurementUnitWhereUniqueInput
}

export type MeasurementUnitUpdateOneRequiredWithoutIngredientGroupOutputsNestedInput = {
  create?: Prisma.XOR<Prisma.MeasurementUnitCreateWithoutIngredientGroupOutputsInput, Prisma.MeasurementUnitUncheckedCreateWithoutIngredientGroupOutputsInput>
  connectOrCreate?: Prisma.MeasurementUnitCreateOrConnectWithoutIngredientGroupOutputsInput
  upsert?: Prisma.MeasurementUnitUpsertWithoutIngredientGroupOutputsInput
  connect?: Prisma.MeasurementUnitWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MeasurementUnitUpdateToOneWithWhereWithoutIngredientGroupOutputsInput, Prisma.MeasurementUnitUpdateWithoutIngredientGroupOutputsInput>, Prisma.MeasurementUnitUncheckedUpdateWithoutIngredientGroupOutputsInput>
}

export type MeasurementUnitCreateWithoutRecipeOutputsInput = {
  id?: string
  name: string
  shortName: string
  kind: $Enums.MeasurementUnitKind
  roundToInteger?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  ingredients?: Prisma.RecipeIngredientCreateNestedManyWithoutUnitInput
  ingredientGroupOutputs?: Prisma.RecipeIngredientGroupCreateNestedManyWithoutOutputUnitInput
}

export type MeasurementUnitUncheckedCreateWithoutRecipeOutputsInput = {
  id?: string
  name: string
  shortName: string
  kind: $Enums.MeasurementUnitKind
  roundToInteger?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  ingredients?: Prisma.RecipeIngredientUncheckedCreateNestedManyWithoutUnitInput
  ingredientGroupOutputs?: Prisma.RecipeIngredientGroupUncheckedCreateNestedManyWithoutOutputUnitInput
}

export type MeasurementUnitCreateOrConnectWithoutRecipeOutputsInput = {
  where: Prisma.MeasurementUnitWhereUniqueInput
  create: Prisma.XOR<Prisma.MeasurementUnitCreateWithoutRecipeOutputsInput, Prisma.MeasurementUnitUncheckedCreateWithoutRecipeOutputsInput>
}

export type MeasurementUnitUpsertWithoutRecipeOutputsInput = {
  update: Prisma.XOR<Prisma.MeasurementUnitUpdateWithoutRecipeOutputsInput, Prisma.MeasurementUnitUncheckedUpdateWithoutRecipeOutputsInput>
  create: Prisma.XOR<Prisma.MeasurementUnitCreateWithoutRecipeOutputsInput, Prisma.MeasurementUnitUncheckedCreateWithoutRecipeOutputsInput>
  where?: Prisma.MeasurementUnitWhereInput
}

export type MeasurementUnitUpdateToOneWithWhereWithoutRecipeOutputsInput = {
  where?: Prisma.MeasurementUnitWhereInput
  data: Prisma.XOR<Prisma.MeasurementUnitUpdateWithoutRecipeOutputsInput, Prisma.MeasurementUnitUncheckedUpdateWithoutRecipeOutputsInput>
}

export type MeasurementUnitUpdateWithoutRecipeOutputsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  shortName?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumMeasurementUnitKindFieldUpdateOperationsInput | $Enums.MeasurementUnitKind
  roundToInteger?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ingredients?: Prisma.RecipeIngredientUpdateManyWithoutUnitNestedInput
  ingredientGroupOutputs?: Prisma.RecipeIngredientGroupUpdateManyWithoutOutputUnitNestedInput
}

export type MeasurementUnitUncheckedUpdateWithoutRecipeOutputsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  shortName?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumMeasurementUnitKindFieldUpdateOperationsInput | $Enums.MeasurementUnitKind
  roundToInteger?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ingredients?: Prisma.RecipeIngredientUncheckedUpdateManyWithoutUnitNestedInput
  ingredientGroupOutputs?: Prisma.RecipeIngredientGroupUncheckedUpdateManyWithoutOutputUnitNestedInput
}

export type MeasurementUnitCreateWithoutIngredientsInput = {
  id?: string
  name: string
  shortName: string
  kind: $Enums.MeasurementUnitKind
  roundToInteger?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  recipeOutputs?: Prisma.RecipeCreateNestedManyWithoutOutputUnitInput
  ingredientGroupOutputs?: Prisma.RecipeIngredientGroupCreateNestedManyWithoutOutputUnitInput
}

export type MeasurementUnitUncheckedCreateWithoutIngredientsInput = {
  id?: string
  name: string
  shortName: string
  kind: $Enums.MeasurementUnitKind
  roundToInteger?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  recipeOutputs?: Prisma.RecipeUncheckedCreateNestedManyWithoutOutputUnitInput
  ingredientGroupOutputs?: Prisma.RecipeIngredientGroupUncheckedCreateNestedManyWithoutOutputUnitInput
}

export type MeasurementUnitCreateOrConnectWithoutIngredientsInput = {
  where: Prisma.MeasurementUnitWhereUniqueInput
  create: Prisma.XOR<Prisma.MeasurementUnitCreateWithoutIngredientsInput, Prisma.MeasurementUnitUncheckedCreateWithoutIngredientsInput>
}

export type MeasurementUnitUpsertWithoutIngredientsInput = {
  update: Prisma.XOR<Prisma.MeasurementUnitUpdateWithoutIngredientsInput, Prisma.MeasurementUnitUncheckedUpdateWithoutIngredientsInput>
  create: Prisma.XOR<Prisma.MeasurementUnitCreateWithoutIngredientsInput, Prisma.MeasurementUnitUncheckedCreateWithoutIngredientsInput>
  where?: Prisma.MeasurementUnitWhereInput
}

export type MeasurementUnitUpdateToOneWithWhereWithoutIngredientsInput = {
  where?: Prisma.MeasurementUnitWhereInput
  data: Prisma.XOR<Prisma.MeasurementUnitUpdateWithoutIngredientsInput, Prisma.MeasurementUnitUncheckedUpdateWithoutIngredientsInput>
}

export type MeasurementUnitUpdateWithoutIngredientsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  shortName?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumMeasurementUnitKindFieldUpdateOperationsInput | $Enums.MeasurementUnitKind
  roundToInteger?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  recipeOutputs?: Prisma.RecipeUpdateManyWithoutOutputUnitNestedInput
  ingredientGroupOutputs?: Prisma.RecipeIngredientGroupUpdateManyWithoutOutputUnitNestedInput
}

export type MeasurementUnitUncheckedUpdateWithoutIngredientsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  shortName?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumMeasurementUnitKindFieldUpdateOperationsInput | $Enums.MeasurementUnitKind
  roundToInteger?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  recipeOutputs?: Prisma.RecipeUncheckedUpdateManyWithoutOutputUnitNestedInput
  ingredientGroupOutputs?: Prisma.RecipeIngredientGroupUncheckedUpdateManyWithoutOutputUnitNestedInput
}

export type MeasurementUnitCreateWithoutIngredientGroupOutputsInput = {
  id?: string
  name: string
  shortName: string
  kind: $Enums.MeasurementUnitKind
  roundToInteger?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  ingredients?: Prisma.RecipeIngredientCreateNestedManyWithoutUnitInput
  recipeOutputs?: Prisma.RecipeCreateNestedManyWithoutOutputUnitInput
}

export type MeasurementUnitUncheckedCreateWithoutIngredientGroupOutputsInput = {
  id?: string
  name: string
  shortName: string
  kind: $Enums.MeasurementUnitKind
  roundToInteger?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  ingredients?: Prisma.RecipeIngredientUncheckedCreateNestedManyWithoutUnitInput
  recipeOutputs?: Prisma.RecipeUncheckedCreateNestedManyWithoutOutputUnitInput
}

export type MeasurementUnitCreateOrConnectWithoutIngredientGroupOutputsInput = {
  where: Prisma.MeasurementUnitWhereUniqueInput
  create: Prisma.XOR<Prisma.MeasurementUnitCreateWithoutIngredientGroupOutputsInput, Prisma.MeasurementUnitUncheckedCreateWithoutIngredientGroupOutputsInput>
}

export type MeasurementUnitUpsertWithoutIngredientGroupOutputsInput = {
  update: Prisma.XOR<Prisma.MeasurementUnitUpdateWithoutIngredientGroupOutputsInput, Prisma.MeasurementUnitUncheckedUpdateWithoutIngredientGroupOutputsInput>
  create: Prisma.XOR<Prisma.MeasurementUnitCreateWithoutIngredientGroupOutputsInput, Prisma.MeasurementUnitUncheckedCreateWithoutIngredientGroupOutputsInput>
  where?: Prisma.MeasurementUnitWhereInput
}

export type MeasurementUnitUpdateToOneWithWhereWithoutIngredientGroupOutputsInput = {
  where?: Prisma.MeasurementUnitWhereInput
  data: Prisma.XOR<Prisma.MeasurementUnitUpdateWithoutIngredientGroupOutputsInput, Prisma.MeasurementUnitUncheckedUpdateWithoutIngredientGroupOutputsInput>
}

export type MeasurementUnitUpdateWithoutIngredientGroupOutputsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  shortName?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumMeasurementUnitKindFieldUpdateOperationsInput | $Enums.MeasurementUnitKind
  roundToInteger?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ingredients?: Prisma.RecipeIngredientUpdateManyWithoutUnitNestedInput
  recipeOutputs?: Prisma.RecipeUpdateManyWithoutOutputUnitNestedInput
}

export type MeasurementUnitUncheckedUpdateWithoutIngredientGroupOutputsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  shortName?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumMeasurementUnitKindFieldUpdateOperationsInput | $Enums.MeasurementUnitKind
  roundToInteger?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ingredients?: Prisma.RecipeIngredientUncheckedUpdateManyWithoutUnitNestedInput
  recipeOutputs?: Prisma.RecipeUncheckedUpdateManyWithoutOutputUnitNestedInput
}


/**
 * Count Type MeasurementUnitCountOutputType
 */

export type MeasurementUnitCountOutputType = {
  ingredients: number
  recipeOutputs: number
  ingredientGroupOutputs: number
}

export type MeasurementUnitCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ingredients?: boolean | MeasurementUnitCountOutputTypeCountIngredientsArgs
  recipeOutputs?: boolean | MeasurementUnitCountOutputTypeCountRecipeOutputsArgs
  ingredientGroupOutputs?: boolean | MeasurementUnitCountOutputTypeCountIngredientGroupOutputsArgs
}

/**
 * MeasurementUnitCountOutputType without action
 */
export type MeasurementUnitCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeasurementUnitCountOutputType
   */
  select?: Prisma.MeasurementUnitCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MeasurementUnitCountOutputType without action
 */
export type MeasurementUnitCountOutputTypeCountIngredientsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecipeIngredientWhereInput
}

/**
 * MeasurementUnitCountOutputType without action
 */
export type MeasurementUnitCountOutputTypeCountRecipeOutputsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecipeWhereInput
}

/**
 * MeasurementUnitCountOutputType without action
 */
export type MeasurementUnitCountOutputTypeCountIngredientGroupOutputsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecipeIngredientGroupWhereInput
}


export type MeasurementUnitSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  shortName?: boolean
  kind?: boolean
  roundToInteger?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  ingredients?: boolean | Prisma.MeasurementUnit$ingredientsArgs<ExtArgs>
  recipeOutputs?: boolean | Prisma.MeasurementUnit$recipeOutputsArgs<ExtArgs>
  ingredientGroupOutputs?: boolean | Prisma.MeasurementUnit$ingredientGroupOutputsArgs<ExtArgs>
  _count?: boolean | Prisma.MeasurementUnitCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["measurementUnit"]>

export type MeasurementUnitSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  shortName?: boolean
  kind?: boolean
  roundToInteger?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["measurementUnit"]>

export type MeasurementUnitSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  shortName?: boolean
  kind?: boolean
  roundToInteger?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["measurementUnit"]>

export type MeasurementUnitSelectScalar = {
  id?: boolean
  name?: boolean
  shortName?: boolean
  kind?: boolean
  roundToInteger?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MeasurementUnitOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "shortName" | "kind" | "roundToInteger" | "createdAt" | "updatedAt", ExtArgs["result"]["measurementUnit"]>
export type MeasurementUnitInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ingredients?: boolean | Prisma.MeasurementUnit$ingredientsArgs<ExtArgs>
  recipeOutputs?: boolean | Prisma.MeasurementUnit$recipeOutputsArgs<ExtArgs>
  ingredientGroupOutputs?: boolean | Prisma.MeasurementUnit$ingredientGroupOutputsArgs<ExtArgs>
  _count?: boolean | Prisma.MeasurementUnitCountOutputTypeDefaultArgs<ExtArgs>
}
export type MeasurementUnitIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type MeasurementUnitIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $MeasurementUnitPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MeasurementUnit"
  objects: {
    ingredients: Prisma.$RecipeIngredientPayload<ExtArgs>[]
    recipeOutputs: Prisma.$RecipePayload<ExtArgs>[]
    ingredientGroupOutputs: Prisma.$RecipeIngredientGroupPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    shortName: string
    kind: $Enums.MeasurementUnitKind
    roundToInteger: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["measurementUnit"]>
  composites: {}
}

export type MeasurementUnitGetPayload<S extends boolean | null | undefined | MeasurementUnitDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MeasurementUnitPayload, S>

export type MeasurementUnitCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MeasurementUnitFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MeasurementUnitCountAggregateInputType | true
  }

export interface MeasurementUnitDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MeasurementUnit'], meta: { name: 'MeasurementUnit' } }
  /**
   * Find zero or one MeasurementUnit that matches the filter.
   * @param {MeasurementUnitFindUniqueArgs} args - Arguments to find a MeasurementUnit
   * @example
   * // Get one MeasurementUnit
   * const measurementUnit = await prisma.measurementUnit.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MeasurementUnitFindUniqueArgs>(args: Prisma.SelectSubset<T, MeasurementUnitFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MeasurementUnitClient<runtime.Types.Result.GetResult<Prisma.$MeasurementUnitPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MeasurementUnit that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MeasurementUnitFindUniqueOrThrowArgs} args - Arguments to find a MeasurementUnit
   * @example
   * // Get one MeasurementUnit
   * const measurementUnit = await prisma.measurementUnit.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MeasurementUnitFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MeasurementUnitFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MeasurementUnitClient<runtime.Types.Result.GetResult<Prisma.$MeasurementUnitPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MeasurementUnit that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MeasurementUnitFindFirstArgs} args - Arguments to find a MeasurementUnit
   * @example
   * // Get one MeasurementUnit
   * const measurementUnit = await prisma.measurementUnit.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MeasurementUnitFindFirstArgs>(args?: Prisma.SelectSubset<T, MeasurementUnitFindFirstArgs<ExtArgs>>): Prisma.Prisma__MeasurementUnitClient<runtime.Types.Result.GetResult<Prisma.$MeasurementUnitPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MeasurementUnit that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MeasurementUnitFindFirstOrThrowArgs} args - Arguments to find a MeasurementUnit
   * @example
   * // Get one MeasurementUnit
   * const measurementUnit = await prisma.measurementUnit.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MeasurementUnitFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MeasurementUnitFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MeasurementUnitClient<runtime.Types.Result.GetResult<Prisma.$MeasurementUnitPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MeasurementUnits that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MeasurementUnitFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MeasurementUnits
   * const measurementUnits = await prisma.measurementUnit.findMany()
   * 
   * // Get first 10 MeasurementUnits
   * const measurementUnits = await prisma.measurementUnit.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const measurementUnitWithIdOnly = await prisma.measurementUnit.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MeasurementUnitFindManyArgs>(args?: Prisma.SelectSubset<T, MeasurementUnitFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MeasurementUnitPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MeasurementUnit.
   * @param {MeasurementUnitCreateArgs} args - Arguments to create a MeasurementUnit.
   * @example
   * // Create one MeasurementUnit
   * const MeasurementUnit = await prisma.measurementUnit.create({
   *   data: {
   *     // ... data to create a MeasurementUnit
   *   }
   * })
   * 
   */
  create<T extends MeasurementUnitCreateArgs>(args: Prisma.SelectSubset<T, MeasurementUnitCreateArgs<ExtArgs>>): Prisma.Prisma__MeasurementUnitClient<runtime.Types.Result.GetResult<Prisma.$MeasurementUnitPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MeasurementUnits.
   * @param {MeasurementUnitCreateManyArgs} args - Arguments to create many MeasurementUnits.
   * @example
   * // Create many MeasurementUnits
   * const measurementUnit = await prisma.measurementUnit.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MeasurementUnitCreateManyArgs>(args?: Prisma.SelectSubset<T, MeasurementUnitCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MeasurementUnits and returns the data saved in the database.
   * @param {MeasurementUnitCreateManyAndReturnArgs} args - Arguments to create many MeasurementUnits.
   * @example
   * // Create many MeasurementUnits
   * const measurementUnit = await prisma.measurementUnit.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MeasurementUnits and only return the `id`
   * const measurementUnitWithIdOnly = await prisma.measurementUnit.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MeasurementUnitCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MeasurementUnitCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MeasurementUnitPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MeasurementUnit.
   * @param {MeasurementUnitDeleteArgs} args - Arguments to delete one MeasurementUnit.
   * @example
   * // Delete one MeasurementUnit
   * const MeasurementUnit = await prisma.measurementUnit.delete({
   *   where: {
   *     // ... filter to delete one MeasurementUnit
   *   }
   * })
   * 
   */
  delete<T extends MeasurementUnitDeleteArgs>(args: Prisma.SelectSubset<T, MeasurementUnitDeleteArgs<ExtArgs>>): Prisma.Prisma__MeasurementUnitClient<runtime.Types.Result.GetResult<Prisma.$MeasurementUnitPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MeasurementUnit.
   * @param {MeasurementUnitUpdateArgs} args - Arguments to update one MeasurementUnit.
   * @example
   * // Update one MeasurementUnit
   * const measurementUnit = await prisma.measurementUnit.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MeasurementUnitUpdateArgs>(args: Prisma.SelectSubset<T, MeasurementUnitUpdateArgs<ExtArgs>>): Prisma.Prisma__MeasurementUnitClient<runtime.Types.Result.GetResult<Prisma.$MeasurementUnitPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MeasurementUnits.
   * @param {MeasurementUnitDeleteManyArgs} args - Arguments to filter MeasurementUnits to delete.
   * @example
   * // Delete a few MeasurementUnits
   * const { count } = await prisma.measurementUnit.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MeasurementUnitDeleteManyArgs>(args?: Prisma.SelectSubset<T, MeasurementUnitDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MeasurementUnits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MeasurementUnitUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MeasurementUnits
   * const measurementUnit = await prisma.measurementUnit.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MeasurementUnitUpdateManyArgs>(args: Prisma.SelectSubset<T, MeasurementUnitUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MeasurementUnits and returns the data updated in the database.
   * @param {MeasurementUnitUpdateManyAndReturnArgs} args - Arguments to update many MeasurementUnits.
   * @example
   * // Update many MeasurementUnits
   * const measurementUnit = await prisma.measurementUnit.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MeasurementUnits and only return the `id`
   * const measurementUnitWithIdOnly = await prisma.measurementUnit.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MeasurementUnitUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MeasurementUnitUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MeasurementUnitPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MeasurementUnit.
   * @param {MeasurementUnitUpsertArgs} args - Arguments to update or create a MeasurementUnit.
   * @example
   * // Update or create a MeasurementUnit
   * const measurementUnit = await prisma.measurementUnit.upsert({
   *   create: {
   *     // ... data to create a MeasurementUnit
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MeasurementUnit we want to update
   *   }
   * })
   */
  upsert<T extends MeasurementUnitUpsertArgs>(args: Prisma.SelectSubset<T, MeasurementUnitUpsertArgs<ExtArgs>>): Prisma.Prisma__MeasurementUnitClient<runtime.Types.Result.GetResult<Prisma.$MeasurementUnitPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MeasurementUnits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MeasurementUnitCountArgs} args - Arguments to filter MeasurementUnits to count.
   * @example
   * // Count the number of MeasurementUnits
   * const count = await prisma.measurementUnit.count({
   *   where: {
   *     // ... the filter for the MeasurementUnits we want to count
   *   }
   * })
  **/
  count<T extends MeasurementUnitCountArgs>(
    args?: Prisma.Subset<T, MeasurementUnitCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MeasurementUnitCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MeasurementUnit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MeasurementUnitAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MeasurementUnitAggregateArgs>(args: Prisma.Subset<T, MeasurementUnitAggregateArgs>): Prisma.PrismaPromise<GetMeasurementUnitAggregateType<T>>

  /**
   * Group by MeasurementUnit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MeasurementUnitGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MeasurementUnitGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MeasurementUnitGroupByArgs['orderBy'] }
      : { orderBy?: MeasurementUnitGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MeasurementUnitGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMeasurementUnitGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MeasurementUnit model
 */
readonly fields: MeasurementUnitFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MeasurementUnit.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MeasurementUnitClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  ingredients<T extends Prisma.MeasurementUnit$ingredientsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MeasurementUnit$ingredientsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipeIngredientPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  recipeOutputs<T extends Prisma.MeasurementUnit$recipeOutputsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MeasurementUnit$recipeOutputsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  ingredientGroupOutputs<T extends Prisma.MeasurementUnit$ingredientGroupOutputsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MeasurementUnit$ingredientGroupOutputsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipeIngredientGroupPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MeasurementUnit model
 */
export interface MeasurementUnitFieldRefs {
  readonly id: Prisma.FieldRef<"MeasurementUnit", 'String'>
  readonly name: Prisma.FieldRef<"MeasurementUnit", 'String'>
  readonly shortName: Prisma.FieldRef<"MeasurementUnit", 'String'>
  readonly kind: Prisma.FieldRef<"MeasurementUnit", 'MeasurementUnitKind'>
  readonly roundToInteger: Prisma.FieldRef<"MeasurementUnit", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"MeasurementUnit", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MeasurementUnit", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MeasurementUnit findUnique
 */
export type MeasurementUnitFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeasurementUnit
   */
  select?: Prisma.MeasurementUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeasurementUnit
   */
  omit?: Prisma.MeasurementUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeasurementUnitInclude<ExtArgs> | null
  /**
   * Filter, which MeasurementUnit to fetch.
   */
  where: Prisma.MeasurementUnitWhereUniqueInput
}

/**
 * MeasurementUnit findUniqueOrThrow
 */
export type MeasurementUnitFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeasurementUnit
   */
  select?: Prisma.MeasurementUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeasurementUnit
   */
  omit?: Prisma.MeasurementUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeasurementUnitInclude<ExtArgs> | null
  /**
   * Filter, which MeasurementUnit to fetch.
   */
  where: Prisma.MeasurementUnitWhereUniqueInput
}

/**
 * MeasurementUnit findFirst
 */
export type MeasurementUnitFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeasurementUnit
   */
  select?: Prisma.MeasurementUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeasurementUnit
   */
  omit?: Prisma.MeasurementUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeasurementUnitInclude<ExtArgs> | null
  /**
   * Filter, which MeasurementUnit to fetch.
   */
  where?: Prisma.MeasurementUnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MeasurementUnits to fetch.
   */
  orderBy?: Prisma.MeasurementUnitOrderByWithRelationInput | Prisma.MeasurementUnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MeasurementUnits.
   */
  cursor?: Prisma.MeasurementUnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MeasurementUnits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MeasurementUnits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MeasurementUnits.
   */
  distinct?: Prisma.MeasurementUnitScalarFieldEnum | Prisma.MeasurementUnitScalarFieldEnum[]
}

/**
 * MeasurementUnit findFirstOrThrow
 */
export type MeasurementUnitFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeasurementUnit
   */
  select?: Prisma.MeasurementUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeasurementUnit
   */
  omit?: Prisma.MeasurementUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeasurementUnitInclude<ExtArgs> | null
  /**
   * Filter, which MeasurementUnit to fetch.
   */
  where?: Prisma.MeasurementUnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MeasurementUnits to fetch.
   */
  orderBy?: Prisma.MeasurementUnitOrderByWithRelationInput | Prisma.MeasurementUnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MeasurementUnits.
   */
  cursor?: Prisma.MeasurementUnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MeasurementUnits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MeasurementUnits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MeasurementUnits.
   */
  distinct?: Prisma.MeasurementUnitScalarFieldEnum | Prisma.MeasurementUnitScalarFieldEnum[]
}

/**
 * MeasurementUnit findMany
 */
export type MeasurementUnitFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeasurementUnit
   */
  select?: Prisma.MeasurementUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeasurementUnit
   */
  omit?: Prisma.MeasurementUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeasurementUnitInclude<ExtArgs> | null
  /**
   * Filter, which MeasurementUnits to fetch.
   */
  where?: Prisma.MeasurementUnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MeasurementUnits to fetch.
   */
  orderBy?: Prisma.MeasurementUnitOrderByWithRelationInput | Prisma.MeasurementUnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MeasurementUnits.
   */
  cursor?: Prisma.MeasurementUnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MeasurementUnits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MeasurementUnits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MeasurementUnits.
   */
  distinct?: Prisma.MeasurementUnitScalarFieldEnum | Prisma.MeasurementUnitScalarFieldEnum[]
}

/**
 * MeasurementUnit create
 */
export type MeasurementUnitCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeasurementUnit
   */
  select?: Prisma.MeasurementUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeasurementUnit
   */
  omit?: Prisma.MeasurementUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeasurementUnitInclude<ExtArgs> | null
  /**
   * The data needed to create a MeasurementUnit.
   */
  data: Prisma.XOR<Prisma.MeasurementUnitCreateInput, Prisma.MeasurementUnitUncheckedCreateInput>
}

/**
 * MeasurementUnit createMany
 */
export type MeasurementUnitCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MeasurementUnits.
   */
  data: Prisma.MeasurementUnitCreateManyInput | Prisma.MeasurementUnitCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MeasurementUnit createManyAndReturn
 */
export type MeasurementUnitCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeasurementUnit
   */
  select?: Prisma.MeasurementUnitSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MeasurementUnit
   */
  omit?: Prisma.MeasurementUnitOmit<ExtArgs> | null
  /**
   * The data used to create many MeasurementUnits.
   */
  data: Prisma.MeasurementUnitCreateManyInput | Prisma.MeasurementUnitCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MeasurementUnit update
 */
export type MeasurementUnitUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeasurementUnit
   */
  select?: Prisma.MeasurementUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeasurementUnit
   */
  omit?: Prisma.MeasurementUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeasurementUnitInclude<ExtArgs> | null
  /**
   * The data needed to update a MeasurementUnit.
   */
  data: Prisma.XOR<Prisma.MeasurementUnitUpdateInput, Prisma.MeasurementUnitUncheckedUpdateInput>
  /**
   * Choose, which MeasurementUnit to update.
   */
  where: Prisma.MeasurementUnitWhereUniqueInput
}

/**
 * MeasurementUnit updateMany
 */
export type MeasurementUnitUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MeasurementUnits.
   */
  data: Prisma.XOR<Prisma.MeasurementUnitUpdateManyMutationInput, Prisma.MeasurementUnitUncheckedUpdateManyInput>
  /**
   * Filter which MeasurementUnits to update
   */
  where?: Prisma.MeasurementUnitWhereInput
  /**
   * Limit how many MeasurementUnits to update.
   */
  limit?: number
}

/**
 * MeasurementUnit updateManyAndReturn
 */
export type MeasurementUnitUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeasurementUnit
   */
  select?: Prisma.MeasurementUnitSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MeasurementUnit
   */
  omit?: Prisma.MeasurementUnitOmit<ExtArgs> | null
  /**
   * The data used to update MeasurementUnits.
   */
  data: Prisma.XOR<Prisma.MeasurementUnitUpdateManyMutationInput, Prisma.MeasurementUnitUncheckedUpdateManyInput>
  /**
   * Filter which MeasurementUnits to update
   */
  where?: Prisma.MeasurementUnitWhereInput
  /**
   * Limit how many MeasurementUnits to update.
   */
  limit?: number
}

/**
 * MeasurementUnit upsert
 */
export type MeasurementUnitUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeasurementUnit
   */
  select?: Prisma.MeasurementUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeasurementUnit
   */
  omit?: Prisma.MeasurementUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeasurementUnitInclude<ExtArgs> | null
  /**
   * The filter to search for the MeasurementUnit to update in case it exists.
   */
  where: Prisma.MeasurementUnitWhereUniqueInput
  /**
   * In case the MeasurementUnit found by the `where` argument doesn't exist, create a new MeasurementUnit with this data.
   */
  create: Prisma.XOR<Prisma.MeasurementUnitCreateInput, Prisma.MeasurementUnitUncheckedCreateInput>
  /**
   * In case the MeasurementUnit was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MeasurementUnitUpdateInput, Prisma.MeasurementUnitUncheckedUpdateInput>
}

/**
 * MeasurementUnit delete
 */
export type MeasurementUnitDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeasurementUnit
   */
  select?: Prisma.MeasurementUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeasurementUnit
   */
  omit?: Prisma.MeasurementUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeasurementUnitInclude<ExtArgs> | null
  /**
   * Filter which MeasurementUnit to delete.
   */
  where: Prisma.MeasurementUnitWhereUniqueInput
}

/**
 * MeasurementUnit deleteMany
 */
export type MeasurementUnitDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MeasurementUnits to delete
   */
  where?: Prisma.MeasurementUnitWhereInput
  /**
   * Limit how many MeasurementUnits to delete.
   */
  limit?: number
}

/**
 * MeasurementUnit.ingredients
 */
export type MeasurementUnit$ingredientsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeIngredient
   */
  select?: Prisma.RecipeIngredientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeIngredient
   */
  omit?: Prisma.RecipeIngredientOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeIngredientInclude<ExtArgs> | null
  where?: Prisma.RecipeIngredientWhereInput
  orderBy?: Prisma.RecipeIngredientOrderByWithRelationInput | Prisma.RecipeIngredientOrderByWithRelationInput[]
  cursor?: Prisma.RecipeIngredientWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RecipeIngredientScalarFieldEnum | Prisma.RecipeIngredientScalarFieldEnum[]
}

/**
 * MeasurementUnit.recipeOutputs
 */
export type MeasurementUnit$recipeOutputsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe
   */
  select?: Prisma.RecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe
   */
  omit?: Prisma.RecipeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeInclude<ExtArgs> | null
  where?: Prisma.RecipeWhereInput
  orderBy?: Prisma.RecipeOrderByWithRelationInput | Prisma.RecipeOrderByWithRelationInput[]
  cursor?: Prisma.RecipeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RecipeScalarFieldEnum | Prisma.RecipeScalarFieldEnum[]
}

/**
 * MeasurementUnit.ingredientGroupOutputs
 */
export type MeasurementUnit$ingredientGroupOutputsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeIngredientGroup
   */
  select?: Prisma.RecipeIngredientGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeIngredientGroup
   */
  omit?: Prisma.RecipeIngredientGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeIngredientGroupInclude<ExtArgs> | null
  where?: Prisma.RecipeIngredientGroupWhereInput
  orderBy?: Prisma.RecipeIngredientGroupOrderByWithRelationInput | Prisma.RecipeIngredientGroupOrderByWithRelationInput[]
  cursor?: Prisma.RecipeIngredientGroupWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RecipeIngredientGroupScalarFieldEnum | Prisma.RecipeIngredientGroupScalarFieldEnum[]
}

/**
 * MeasurementUnit without action
 */
export type MeasurementUnitDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeasurementUnit
   */
  select?: Prisma.MeasurementUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeasurementUnit
   */
  omit?: Prisma.MeasurementUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeasurementUnitInclude<ExtArgs> | null
}
