
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RecipeEquipment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RecipeEquipment
 * 
 */
export type RecipeEquipmentModel = runtime.Types.Result.DefaultSelection<Prisma.$RecipeEquipmentPayload>

export type AggregateRecipeEquipment = {
  _count: RecipeEquipmentCountAggregateOutputType | null
  _avg: RecipeEquipmentAvgAggregateOutputType | null
  _sum: RecipeEquipmentSumAggregateOutputType | null
  _min: RecipeEquipmentMinAggregateOutputType | null
  _max: RecipeEquipmentMaxAggregateOutputType | null
}

export type RecipeEquipmentAvgAggregateOutputType = {
  order: number | null
}

export type RecipeEquipmentSumAggregateOutputType = {
  order: number | null
}

export type RecipeEquipmentMinAggregateOutputType = {
  id: string | null
  recipeId: string | null
  order: number | null
  label: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RecipeEquipmentMaxAggregateOutputType = {
  id: string | null
  recipeId: string | null
  order: number | null
  label: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RecipeEquipmentCountAggregateOutputType = {
  id: number
  recipeId: number
  order: number
  label: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type RecipeEquipmentAvgAggregateInputType = {
  order?: true
}

export type RecipeEquipmentSumAggregateInputType = {
  order?: true
}

export type RecipeEquipmentMinAggregateInputType = {
  id?: true
  recipeId?: true
  order?: true
  label?: true
  createdAt?: true
  updatedAt?: true
}

export type RecipeEquipmentMaxAggregateInputType = {
  id?: true
  recipeId?: true
  order?: true
  label?: true
  createdAt?: true
  updatedAt?: true
}

export type RecipeEquipmentCountAggregateInputType = {
  id?: true
  recipeId?: true
  order?: true
  label?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type RecipeEquipmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecipeEquipment to aggregate.
   */
  where?: Prisma.RecipeEquipmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipeEquipments to fetch.
   */
  orderBy?: Prisma.RecipeEquipmentOrderByWithRelationInput | Prisma.RecipeEquipmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RecipeEquipmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipeEquipments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipeEquipments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RecipeEquipments
  **/
  _count?: true | RecipeEquipmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RecipeEquipmentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RecipeEquipmentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RecipeEquipmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RecipeEquipmentMaxAggregateInputType
}

export type GetRecipeEquipmentAggregateType<T extends RecipeEquipmentAggregateArgs> = {
      [P in keyof T & keyof AggregateRecipeEquipment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRecipeEquipment[P]>
    : Prisma.GetScalarType<T[P], AggregateRecipeEquipment[P]>
}




export type RecipeEquipmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecipeEquipmentWhereInput
  orderBy?: Prisma.RecipeEquipmentOrderByWithAggregationInput | Prisma.RecipeEquipmentOrderByWithAggregationInput[]
  by: Prisma.RecipeEquipmentScalarFieldEnum[] | Prisma.RecipeEquipmentScalarFieldEnum
  having?: Prisma.RecipeEquipmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RecipeEquipmentCountAggregateInputType | true
  _avg?: RecipeEquipmentAvgAggregateInputType
  _sum?: RecipeEquipmentSumAggregateInputType
  _min?: RecipeEquipmentMinAggregateInputType
  _max?: RecipeEquipmentMaxAggregateInputType
}

export type RecipeEquipmentGroupByOutputType = {
  id: string
  recipeId: string
  order: number
  label: string
  createdAt: Date
  updatedAt: Date
  _count: RecipeEquipmentCountAggregateOutputType | null
  _avg: RecipeEquipmentAvgAggregateOutputType | null
  _sum: RecipeEquipmentSumAggregateOutputType | null
  _min: RecipeEquipmentMinAggregateOutputType | null
  _max: RecipeEquipmentMaxAggregateOutputType | null
}

export type GetRecipeEquipmentGroupByPayload<T extends RecipeEquipmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RecipeEquipmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RecipeEquipmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RecipeEquipmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RecipeEquipmentGroupByOutputType[P]>
      }
    >
  >



export type RecipeEquipmentWhereInput = {
  AND?: Prisma.RecipeEquipmentWhereInput | Prisma.RecipeEquipmentWhereInput[]
  OR?: Prisma.RecipeEquipmentWhereInput[]
  NOT?: Prisma.RecipeEquipmentWhereInput | Prisma.RecipeEquipmentWhereInput[]
  id?: Prisma.StringFilter<"RecipeEquipment"> | string
  recipeId?: Prisma.StringFilter<"RecipeEquipment"> | string
  order?: Prisma.IntFilter<"RecipeEquipment"> | number
  label?: Prisma.StringFilter<"RecipeEquipment"> | string
  createdAt?: Prisma.DateTimeFilter<"RecipeEquipment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RecipeEquipment"> | Date | string
  recipe?: Prisma.XOR<Prisma.RecipeScalarRelationFilter, Prisma.RecipeWhereInput>
}

export type RecipeEquipmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  recipeId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  label?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  recipe?: Prisma.RecipeOrderByWithRelationInput
}

export type RecipeEquipmentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RecipeEquipmentWhereInput | Prisma.RecipeEquipmentWhereInput[]
  OR?: Prisma.RecipeEquipmentWhereInput[]
  NOT?: Prisma.RecipeEquipmentWhereInput | Prisma.RecipeEquipmentWhereInput[]
  recipeId?: Prisma.StringFilter<"RecipeEquipment"> | string
  order?: Prisma.IntFilter<"RecipeEquipment"> | number
  label?: Prisma.StringFilter<"RecipeEquipment"> | string
  createdAt?: Prisma.DateTimeFilter<"RecipeEquipment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RecipeEquipment"> | Date | string
  recipe?: Prisma.XOR<Prisma.RecipeScalarRelationFilter, Prisma.RecipeWhereInput>
}, "id">

export type RecipeEquipmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  recipeId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  label?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.RecipeEquipmentCountOrderByAggregateInput
  _avg?: Prisma.RecipeEquipmentAvgOrderByAggregateInput
  _max?: Prisma.RecipeEquipmentMaxOrderByAggregateInput
  _min?: Prisma.RecipeEquipmentMinOrderByAggregateInput
  _sum?: Prisma.RecipeEquipmentSumOrderByAggregateInput
}

export type RecipeEquipmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.RecipeEquipmentScalarWhereWithAggregatesInput | Prisma.RecipeEquipmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.RecipeEquipmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RecipeEquipmentScalarWhereWithAggregatesInput | Prisma.RecipeEquipmentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RecipeEquipment"> | string
  recipeId?: Prisma.StringWithAggregatesFilter<"RecipeEquipment"> | string
  order?: Prisma.IntWithAggregatesFilter<"RecipeEquipment"> | number
  label?: Prisma.StringWithAggregatesFilter<"RecipeEquipment"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RecipeEquipment"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"RecipeEquipment"> | Date | string
}

export type RecipeEquipmentCreateInput = {
  id?: string
  order: number
  label: string
  createdAt?: Date | string
  updatedAt?: Date | string
  recipe: Prisma.RecipeCreateNestedOneWithoutEquipmentInput
}

export type RecipeEquipmentUncheckedCreateInput = {
  id?: string
  recipeId: string
  order: number
  label: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecipeEquipmentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  recipe?: Prisma.RecipeUpdateOneRequiredWithoutEquipmentNestedInput
}

export type RecipeEquipmentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipeId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecipeEquipmentCreateManyInput = {
  id?: string
  recipeId: string
  order: number
  label: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecipeEquipmentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecipeEquipmentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipeId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecipeEquipmentListRelationFilter = {
  every?: Prisma.RecipeEquipmentWhereInput
  some?: Prisma.RecipeEquipmentWhereInput
  none?: Prisma.RecipeEquipmentWhereInput
}

export type RecipeEquipmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RecipeEquipmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  recipeId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  label?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RecipeEquipmentAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type RecipeEquipmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  recipeId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  label?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RecipeEquipmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  recipeId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  label?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RecipeEquipmentSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type RecipeEquipmentCreateNestedManyWithoutRecipeInput = {
  create?: Prisma.XOR<Prisma.RecipeEquipmentCreateWithoutRecipeInput, Prisma.RecipeEquipmentUncheckedCreateWithoutRecipeInput> | Prisma.RecipeEquipmentCreateWithoutRecipeInput[] | Prisma.RecipeEquipmentUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipeEquipmentCreateOrConnectWithoutRecipeInput | Prisma.RecipeEquipmentCreateOrConnectWithoutRecipeInput[]
  createMany?: Prisma.RecipeEquipmentCreateManyRecipeInputEnvelope
  connect?: Prisma.RecipeEquipmentWhereUniqueInput | Prisma.RecipeEquipmentWhereUniqueInput[]
}

export type RecipeEquipmentUncheckedCreateNestedManyWithoutRecipeInput = {
  create?: Prisma.XOR<Prisma.RecipeEquipmentCreateWithoutRecipeInput, Prisma.RecipeEquipmentUncheckedCreateWithoutRecipeInput> | Prisma.RecipeEquipmentCreateWithoutRecipeInput[] | Prisma.RecipeEquipmentUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipeEquipmentCreateOrConnectWithoutRecipeInput | Prisma.RecipeEquipmentCreateOrConnectWithoutRecipeInput[]
  createMany?: Prisma.RecipeEquipmentCreateManyRecipeInputEnvelope
  connect?: Prisma.RecipeEquipmentWhereUniqueInput | Prisma.RecipeEquipmentWhereUniqueInput[]
}

export type RecipeEquipmentUpdateManyWithoutRecipeNestedInput = {
  create?: Prisma.XOR<Prisma.RecipeEquipmentCreateWithoutRecipeInput, Prisma.RecipeEquipmentUncheckedCreateWithoutRecipeInput> | Prisma.RecipeEquipmentCreateWithoutRecipeInput[] | Prisma.RecipeEquipmentUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipeEquipmentCreateOrConnectWithoutRecipeInput | Prisma.RecipeEquipmentCreateOrConnectWithoutRecipeInput[]
  upsert?: Prisma.RecipeEquipmentUpsertWithWhereUniqueWithoutRecipeInput | Prisma.RecipeEquipmentUpsertWithWhereUniqueWithoutRecipeInput[]
  createMany?: Prisma.RecipeEquipmentCreateManyRecipeInputEnvelope
  set?: Prisma.RecipeEquipmentWhereUniqueInput | Prisma.RecipeEquipmentWhereUniqueInput[]
  disconnect?: Prisma.RecipeEquipmentWhereUniqueInput | Prisma.RecipeEquipmentWhereUniqueInput[]
  delete?: Prisma.RecipeEquipmentWhereUniqueInput | Prisma.RecipeEquipmentWhereUniqueInput[]
  connect?: Prisma.RecipeEquipmentWhereUniqueInput | Prisma.RecipeEquipmentWhereUniqueInput[]
  update?: Prisma.RecipeEquipmentUpdateWithWhereUniqueWithoutRecipeInput | Prisma.RecipeEquipmentUpdateWithWhereUniqueWithoutRecipeInput[]
  updateMany?: Prisma.RecipeEquipmentUpdateManyWithWhereWithoutRecipeInput | Prisma.RecipeEquipmentUpdateManyWithWhereWithoutRecipeInput[]
  deleteMany?: Prisma.RecipeEquipmentScalarWhereInput | Prisma.RecipeEquipmentScalarWhereInput[]
}

export type RecipeEquipmentUncheckedUpdateManyWithoutRecipeNestedInput = {
  create?: Prisma.XOR<Prisma.RecipeEquipmentCreateWithoutRecipeInput, Prisma.RecipeEquipmentUncheckedCreateWithoutRecipeInput> | Prisma.RecipeEquipmentCreateWithoutRecipeInput[] | Prisma.RecipeEquipmentUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipeEquipmentCreateOrConnectWithoutRecipeInput | Prisma.RecipeEquipmentCreateOrConnectWithoutRecipeInput[]
  upsert?: Prisma.RecipeEquipmentUpsertWithWhereUniqueWithoutRecipeInput | Prisma.RecipeEquipmentUpsertWithWhereUniqueWithoutRecipeInput[]
  createMany?: Prisma.RecipeEquipmentCreateManyRecipeInputEnvelope
  set?: Prisma.RecipeEquipmentWhereUniqueInput | Prisma.RecipeEquipmentWhereUniqueInput[]
  disconnect?: Prisma.RecipeEquipmentWhereUniqueInput | Prisma.RecipeEquipmentWhereUniqueInput[]
  delete?: Prisma.RecipeEquipmentWhereUniqueInput | Prisma.RecipeEquipmentWhereUniqueInput[]
  connect?: Prisma.RecipeEquipmentWhereUniqueInput | Prisma.RecipeEquipmentWhereUniqueInput[]
  update?: Prisma.RecipeEquipmentUpdateWithWhereUniqueWithoutRecipeInput | Prisma.RecipeEquipmentUpdateWithWhereUniqueWithoutRecipeInput[]
  updateMany?: Prisma.RecipeEquipmentUpdateManyWithWhereWithoutRecipeInput | Prisma.RecipeEquipmentUpdateManyWithWhereWithoutRecipeInput[]
  deleteMany?: Prisma.RecipeEquipmentScalarWhereInput | Prisma.RecipeEquipmentScalarWhereInput[]
}

export type RecipeEquipmentCreateWithoutRecipeInput = {
  id?: string
  order: number
  label: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecipeEquipmentUncheckedCreateWithoutRecipeInput = {
  id?: string
  order: number
  label: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecipeEquipmentCreateOrConnectWithoutRecipeInput = {
  where: Prisma.RecipeEquipmentWhereUniqueInput
  create: Prisma.XOR<Prisma.RecipeEquipmentCreateWithoutRecipeInput, Prisma.RecipeEquipmentUncheckedCreateWithoutRecipeInput>
}

export type RecipeEquipmentCreateManyRecipeInputEnvelope = {
  data: Prisma.RecipeEquipmentCreateManyRecipeInput | Prisma.RecipeEquipmentCreateManyRecipeInput[]
  skipDuplicates?: boolean
}

export type RecipeEquipmentUpsertWithWhereUniqueWithoutRecipeInput = {
  where: Prisma.RecipeEquipmentWhereUniqueInput
  update: Prisma.XOR<Prisma.RecipeEquipmentUpdateWithoutRecipeInput, Prisma.RecipeEquipmentUncheckedUpdateWithoutRecipeInput>
  create: Prisma.XOR<Prisma.RecipeEquipmentCreateWithoutRecipeInput, Prisma.RecipeEquipmentUncheckedCreateWithoutRecipeInput>
}

export type RecipeEquipmentUpdateWithWhereUniqueWithoutRecipeInput = {
  where: Prisma.RecipeEquipmentWhereUniqueInput
  data: Prisma.XOR<Prisma.RecipeEquipmentUpdateWithoutRecipeInput, Prisma.RecipeEquipmentUncheckedUpdateWithoutRecipeInput>
}

export type RecipeEquipmentUpdateManyWithWhereWithoutRecipeInput = {
  where: Prisma.RecipeEquipmentScalarWhereInput
  data: Prisma.XOR<Prisma.RecipeEquipmentUpdateManyMutationInput, Prisma.RecipeEquipmentUncheckedUpdateManyWithoutRecipeInput>
}

export type RecipeEquipmentScalarWhereInput = {
  AND?: Prisma.RecipeEquipmentScalarWhereInput | Prisma.RecipeEquipmentScalarWhereInput[]
  OR?: Prisma.RecipeEquipmentScalarWhereInput[]
  NOT?: Prisma.RecipeEquipmentScalarWhereInput | Prisma.RecipeEquipmentScalarWhereInput[]
  id?: Prisma.StringFilter<"RecipeEquipment"> | string
  recipeId?: Prisma.StringFilter<"RecipeEquipment"> | string
  order?: Prisma.IntFilter<"RecipeEquipment"> | number
  label?: Prisma.StringFilter<"RecipeEquipment"> | string
  createdAt?: Prisma.DateTimeFilter<"RecipeEquipment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RecipeEquipment"> | Date | string
}

export type RecipeEquipmentCreateManyRecipeInput = {
  id?: string
  order: number
  label: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecipeEquipmentUpdateWithoutRecipeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecipeEquipmentUncheckedUpdateWithoutRecipeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecipeEquipmentUncheckedUpdateManyWithoutRecipeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type RecipeEquipmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  recipeId?: boolean
  order?: boolean
  label?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipeEquipment"]>

export type RecipeEquipmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  recipeId?: boolean
  order?: boolean
  label?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipeEquipment"]>

export type RecipeEquipmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  recipeId?: boolean
  order?: boolean
  label?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipeEquipment"]>

export type RecipeEquipmentSelectScalar = {
  id?: boolean
  recipeId?: boolean
  order?: boolean
  label?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type RecipeEquipmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "recipeId" | "order" | "label" | "createdAt" | "updatedAt", ExtArgs["result"]["recipeEquipment"]>
export type RecipeEquipmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}
export type RecipeEquipmentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}
export type RecipeEquipmentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}

export type $RecipeEquipmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RecipeEquipment"
  objects: {
    recipe: Prisma.$RecipePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    recipeId: string
    order: number
    label: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["recipeEquipment"]>
  composites: {}
}

export type RecipeEquipmentGetPayload<S extends boolean | null | undefined | RecipeEquipmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RecipeEquipmentPayload, S>

export type RecipeEquipmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RecipeEquipmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RecipeEquipmentCountAggregateInputType | true
  }

export interface RecipeEquipmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RecipeEquipment'], meta: { name: 'RecipeEquipment' } }
  /**
   * Find zero or one RecipeEquipment that matches the filter.
   * @param {RecipeEquipmentFindUniqueArgs} args - Arguments to find a RecipeEquipment
   * @example
   * // Get one RecipeEquipment
   * const recipeEquipment = await prisma.recipeEquipment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RecipeEquipmentFindUniqueArgs>(args: Prisma.SelectSubset<T, RecipeEquipmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RecipeEquipmentClient<runtime.Types.Result.GetResult<Prisma.$RecipeEquipmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RecipeEquipment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RecipeEquipmentFindUniqueOrThrowArgs} args - Arguments to find a RecipeEquipment
   * @example
   * // Get one RecipeEquipment
   * const recipeEquipment = await prisma.recipeEquipment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RecipeEquipmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RecipeEquipmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecipeEquipmentClient<runtime.Types.Result.GetResult<Prisma.$RecipeEquipmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecipeEquipment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeEquipmentFindFirstArgs} args - Arguments to find a RecipeEquipment
   * @example
   * // Get one RecipeEquipment
   * const recipeEquipment = await prisma.recipeEquipment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RecipeEquipmentFindFirstArgs>(args?: Prisma.SelectSubset<T, RecipeEquipmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__RecipeEquipmentClient<runtime.Types.Result.GetResult<Prisma.$RecipeEquipmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecipeEquipment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeEquipmentFindFirstOrThrowArgs} args - Arguments to find a RecipeEquipment
   * @example
   * // Get one RecipeEquipment
   * const recipeEquipment = await prisma.recipeEquipment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RecipeEquipmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RecipeEquipmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecipeEquipmentClient<runtime.Types.Result.GetResult<Prisma.$RecipeEquipmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RecipeEquipments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeEquipmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RecipeEquipments
   * const recipeEquipments = await prisma.recipeEquipment.findMany()
   * 
   * // Get first 10 RecipeEquipments
   * const recipeEquipments = await prisma.recipeEquipment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const recipeEquipmentWithIdOnly = await prisma.recipeEquipment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RecipeEquipmentFindManyArgs>(args?: Prisma.SelectSubset<T, RecipeEquipmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipeEquipmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RecipeEquipment.
   * @param {RecipeEquipmentCreateArgs} args - Arguments to create a RecipeEquipment.
   * @example
   * // Create one RecipeEquipment
   * const RecipeEquipment = await prisma.recipeEquipment.create({
   *   data: {
   *     // ... data to create a RecipeEquipment
   *   }
   * })
   * 
   */
  create<T extends RecipeEquipmentCreateArgs>(args: Prisma.SelectSubset<T, RecipeEquipmentCreateArgs<ExtArgs>>): Prisma.Prisma__RecipeEquipmentClient<runtime.Types.Result.GetResult<Prisma.$RecipeEquipmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RecipeEquipments.
   * @param {RecipeEquipmentCreateManyArgs} args - Arguments to create many RecipeEquipments.
   * @example
   * // Create many RecipeEquipments
   * const recipeEquipment = await prisma.recipeEquipment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RecipeEquipmentCreateManyArgs>(args?: Prisma.SelectSubset<T, RecipeEquipmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RecipeEquipments and returns the data saved in the database.
   * @param {RecipeEquipmentCreateManyAndReturnArgs} args - Arguments to create many RecipeEquipments.
   * @example
   * // Create many RecipeEquipments
   * const recipeEquipment = await prisma.recipeEquipment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RecipeEquipments and only return the `id`
   * const recipeEquipmentWithIdOnly = await prisma.recipeEquipment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RecipeEquipmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RecipeEquipmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipeEquipmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RecipeEquipment.
   * @param {RecipeEquipmentDeleteArgs} args - Arguments to delete one RecipeEquipment.
   * @example
   * // Delete one RecipeEquipment
   * const RecipeEquipment = await prisma.recipeEquipment.delete({
   *   where: {
   *     // ... filter to delete one RecipeEquipment
   *   }
   * })
   * 
   */
  delete<T extends RecipeEquipmentDeleteArgs>(args: Prisma.SelectSubset<T, RecipeEquipmentDeleteArgs<ExtArgs>>): Prisma.Prisma__RecipeEquipmentClient<runtime.Types.Result.GetResult<Prisma.$RecipeEquipmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RecipeEquipment.
   * @param {RecipeEquipmentUpdateArgs} args - Arguments to update one RecipeEquipment.
   * @example
   * // Update one RecipeEquipment
   * const recipeEquipment = await prisma.recipeEquipment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RecipeEquipmentUpdateArgs>(args: Prisma.SelectSubset<T, RecipeEquipmentUpdateArgs<ExtArgs>>): Prisma.Prisma__RecipeEquipmentClient<runtime.Types.Result.GetResult<Prisma.$RecipeEquipmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RecipeEquipments.
   * @param {RecipeEquipmentDeleteManyArgs} args - Arguments to filter RecipeEquipments to delete.
   * @example
   * // Delete a few RecipeEquipments
   * const { count } = await prisma.recipeEquipment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RecipeEquipmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, RecipeEquipmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecipeEquipments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeEquipmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RecipeEquipments
   * const recipeEquipment = await prisma.recipeEquipment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RecipeEquipmentUpdateManyArgs>(args: Prisma.SelectSubset<T, RecipeEquipmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecipeEquipments and returns the data updated in the database.
   * @param {RecipeEquipmentUpdateManyAndReturnArgs} args - Arguments to update many RecipeEquipments.
   * @example
   * // Update many RecipeEquipments
   * const recipeEquipment = await prisma.recipeEquipment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RecipeEquipments and only return the `id`
   * const recipeEquipmentWithIdOnly = await prisma.recipeEquipment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RecipeEquipmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RecipeEquipmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipeEquipmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RecipeEquipment.
   * @param {RecipeEquipmentUpsertArgs} args - Arguments to update or create a RecipeEquipment.
   * @example
   * // Update or create a RecipeEquipment
   * const recipeEquipment = await prisma.recipeEquipment.upsert({
   *   create: {
   *     // ... data to create a RecipeEquipment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RecipeEquipment we want to update
   *   }
   * })
   */
  upsert<T extends RecipeEquipmentUpsertArgs>(args: Prisma.SelectSubset<T, RecipeEquipmentUpsertArgs<ExtArgs>>): Prisma.Prisma__RecipeEquipmentClient<runtime.Types.Result.GetResult<Prisma.$RecipeEquipmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RecipeEquipments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeEquipmentCountArgs} args - Arguments to filter RecipeEquipments to count.
   * @example
   * // Count the number of RecipeEquipments
   * const count = await prisma.recipeEquipment.count({
   *   where: {
   *     // ... the filter for the RecipeEquipments we want to count
   *   }
   * })
  **/
  count<T extends RecipeEquipmentCountArgs>(
    args?: Prisma.Subset<T, RecipeEquipmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RecipeEquipmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RecipeEquipment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeEquipmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RecipeEquipmentAggregateArgs>(args: Prisma.Subset<T, RecipeEquipmentAggregateArgs>): Prisma.PrismaPromise<GetRecipeEquipmentAggregateType<T>>

  /**
   * Group by RecipeEquipment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeEquipmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RecipeEquipmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RecipeEquipmentGroupByArgs['orderBy'] }
      : { orderBy?: RecipeEquipmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RecipeEquipmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRecipeEquipmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RecipeEquipment model
 */
readonly fields: RecipeEquipmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RecipeEquipment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RecipeEquipmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  recipe<T extends Prisma.RecipeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RecipeDefaultArgs<ExtArgs>>): Prisma.Prisma__RecipeClient<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RecipeEquipment model
 */
export interface RecipeEquipmentFieldRefs {
  readonly id: Prisma.FieldRef<"RecipeEquipment", 'String'>
  readonly recipeId: Prisma.FieldRef<"RecipeEquipment", 'String'>
  readonly order: Prisma.FieldRef<"RecipeEquipment", 'Int'>
  readonly label: Prisma.FieldRef<"RecipeEquipment", 'String'>
  readonly createdAt: Prisma.FieldRef<"RecipeEquipment", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"RecipeEquipment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RecipeEquipment findUnique
 */
export type RecipeEquipmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeEquipment
   */
  select?: Prisma.RecipeEquipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeEquipment
   */
  omit?: Prisma.RecipeEquipmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeEquipmentInclude<ExtArgs> | null
  /**
   * Filter, which RecipeEquipment to fetch.
   */
  where: Prisma.RecipeEquipmentWhereUniqueInput
}

/**
 * RecipeEquipment findUniqueOrThrow
 */
export type RecipeEquipmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeEquipment
   */
  select?: Prisma.RecipeEquipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeEquipment
   */
  omit?: Prisma.RecipeEquipmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeEquipmentInclude<ExtArgs> | null
  /**
   * Filter, which RecipeEquipment to fetch.
   */
  where: Prisma.RecipeEquipmentWhereUniqueInput
}

/**
 * RecipeEquipment findFirst
 */
export type RecipeEquipmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeEquipment
   */
  select?: Prisma.RecipeEquipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeEquipment
   */
  omit?: Prisma.RecipeEquipmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeEquipmentInclude<ExtArgs> | null
  /**
   * Filter, which RecipeEquipment to fetch.
   */
  where?: Prisma.RecipeEquipmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipeEquipments to fetch.
   */
  orderBy?: Prisma.RecipeEquipmentOrderByWithRelationInput | Prisma.RecipeEquipmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecipeEquipments.
   */
  cursor?: Prisma.RecipeEquipmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipeEquipments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipeEquipments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecipeEquipments.
   */
  distinct?: Prisma.RecipeEquipmentScalarFieldEnum | Prisma.RecipeEquipmentScalarFieldEnum[]
}

/**
 * RecipeEquipment findFirstOrThrow
 */
export type RecipeEquipmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeEquipment
   */
  select?: Prisma.RecipeEquipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeEquipment
   */
  omit?: Prisma.RecipeEquipmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeEquipmentInclude<ExtArgs> | null
  /**
   * Filter, which RecipeEquipment to fetch.
   */
  where?: Prisma.RecipeEquipmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipeEquipments to fetch.
   */
  orderBy?: Prisma.RecipeEquipmentOrderByWithRelationInput | Prisma.RecipeEquipmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecipeEquipments.
   */
  cursor?: Prisma.RecipeEquipmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipeEquipments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipeEquipments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecipeEquipments.
   */
  distinct?: Prisma.RecipeEquipmentScalarFieldEnum | Prisma.RecipeEquipmentScalarFieldEnum[]
}

/**
 * RecipeEquipment findMany
 */
export type RecipeEquipmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeEquipment
   */
  select?: Prisma.RecipeEquipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeEquipment
   */
  omit?: Prisma.RecipeEquipmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeEquipmentInclude<ExtArgs> | null
  /**
   * Filter, which RecipeEquipments to fetch.
   */
  where?: Prisma.RecipeEquipmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipeEquipments to fetch.
   */
  orderBy?: Prisma.RecipeEquipmentOrderByWithRelationInput | Prisma.RecipeEquipmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RecipeEquipments.
   */
  cursor?: Prisma.RecipeEquipmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipeEquipments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipeEquipments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecipeEquipments.
   */
  distinct?: Prisma.RecipeEquipmentScalarFieldEnum | Prisma.RecipeEquipmentScalarFieldEnum[]
}

/**
 * RecipeEquipment create
 */
export type RecipeEquipmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeEquipment
   */
  select?: Prisma.RecipeEquipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeEquipment
   */
  omit?: Prisma.RecipeEquipmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeEquipmentInclude<ExtArgs> | null
  /**
   * The data needed to create a RecipeEquipment.
   */
  data: Prisma.XOR<Prisma.RecipeEquipmentCreateInput, Prisma.RecipeEquipmentUncheckedCreateInput>
}

/**
 * RecipeEquipment createMany
 */
export type RecipeEquipmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RecipeEquipments.
   */
  data: Prisma.RecipeEquipmentCreateManyInput | Prisma.RecipeEquipmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RecipeEquipment createManyAndReturn
 */
export type RecipeEquipmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeEquipment
   */
  select?: Prisma.RecipeEquipmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeEquipment
   */
  omit?: Prisma.RecipeEquipmentOmit<ExtArgs> | null
  /**
   * The data used to create many RecipeEquipments.
   */
  data: Prisma.RecipeEquipmentCreateManyInput | Prisma.RecipeEquipmentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeEquipmentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RecipeEquipment update
 */
export type RecipeEquipmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeEquipment
   */
  select?: Prisma.RecipeEquipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeEquipment
   */
  omit?: Prisma.RecipeEquipmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeEquipmentInclude<ExtArgs> | null
  /**
   * The data needed to update a RecipeEquipment.
   */
  data: Prisma.XOR<Prisma.RecipeEquipmentUpdateInput, Prisma.RecipeEquipmentUncheckedUpdateInput>
  /**
   * Choose, which RecipeEquipment to update.
   */
  where: Prisma.RecipeEquipmentWhereUniqueInput
}

/**
 * RecipeEquipment updateMany
 */
export type RecipeEquipmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RecipeEquipments.
   */
  data: Prisma.XOR<Prisma.RecipeEquipmentUpdateManyMutationInput, Prisma.RecipeEquipmentUncheckedUpdateManyInput>
  /**
   * Filter which RecipeEquipments to update
   */
  where?: Prisma.RecipeEquipmentWhereInput
  /**
   * Limit how many RecipeEquipments to update.
   */
  limit?: number
}

/**
 * RecipeEquipment updateManyAndReturn
 */
export type RecipeEquipmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeEquipment
   */
  select?: Prisma.RecipeEquipmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeEquipment
   */
  omit?: Prisma.RecipeEquipmentOmit<ExtArgs> | null
  /**
   * The data used to update RecipeEquipments.
   */
  data: Prisma.XOR<Prisma.RecipeEquipmentUpdateManyMutationInput, Prisma.RecipeEquipmentUncheckedUpdateManyInput>
  /**
   * Filter which RecipeEquipments to update
   */
  where?: Prisma.RecipeEquipmentWhereInput
  /**
   * Limit how many RecipeEquipments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeEquipmentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RecipeEquipment upsert
 */
export type RecipeEquipmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeEquipment
   */
  select?: Prisma.RecipeEquipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeEquipment
   */
  omit?: Prisma.RecipeEquipmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeEquipmentInclude<ExtArgs> | null
  /**
   * The filter to search for the RecipeEquipment to update in case it exists.
   */
  where: Prisma.RecipeEquipmentWhereUniqueInput
  /**
   * In case the RecipeEquipment found by the `where` argument doesn't exist, create a new RecipeEquipment with this data.
   */
  create: Prisma.XOR<Prisma.RecipeEquipmentCreateInput, Prisma.RecipeEquipmentUncheckedCreateInput>
  /**
   * In case the RecipeEquipment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RecipeEquipmentUpdateInput, Prisma.RecipeEquipmentUncheckedUpdateInput>
}

/**
 * RecipeEquipment delete
 */
export type RecipeEquipmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeEquipment
   */
  select?: Prisma.RecipeEquipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeEquipment
   */
  omit?: Prisma.RecipeEquipmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeEquipmentInclude<ExtArgs> | null
  /**
   * Filter which RecipeEquipment to delete.
   */
  where: Prisma.RecipeEquipmentWhereUniqueInput
}

/**
 * RecipeEquipment deleteMany
 */
export type RecipeEquipmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecipeEquipments to delete
   */
  where?: Prisma.RecipeEquipmentWhereInput
  /**
   * Limit how many RecipeEquipments to delete.
   */
  limit?: number
}

/**
 * RecipeEquipment without action
 */
export type RecipeEquipmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeEquipment
   */
  select?: Prisma.RecipeEquipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeEquipment
   */
  omit?: Prisma.RecipeEquipmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeEquipmentInclude<ExtArgs> | null
}
