
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RecipeNutrition` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RecipeNutrition
 * 
 */
export type RecipeNutritionModel = runtime.Types.Result.DefaultSelection<Prisma.$RecipeNutritionPayload>

export type AggregateRecipeNutrition = {
  _count: RecipeNutritionCountAggregateOutputType | null
  _avg: RecipeNutritionAvgAggregateOutputType | null
  _sum: RecipeNutritionSumAggregateOutputType | null
  _min: RecipeNutritionMinAggregateOutputType | null
  _max: RecipeNutritionMaxAggregateOutputType | null
}

export type RecipeNutritionAvgAggregateOutputType = {
  calories: number | null
  protein: runtime.Decimal | null
  fat: runtime.Decimal | null
  carbs: runtime.Decimal | null
}

export type RecipeNutritionSumAggregateOutputType = {
  calories: number | null
  protein: runtime.Decimal | null
  fat: runtime.Decimal | null
  carbs: runtime.Decimal | null
}

export type RecipeNutritionMinAggregateOutputType = {
  id: string | null
  recipeId: string | null
  calories: number | null
  protein: runtime.Decimal | null
  fat: runtime.Decimal | null
  carbs: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RecipeNutritionMaxAggregateOutputType = {
  id: string | null
  recipeId: string | null
  calories: number | null
  protein: runtime.Decimal | null
  fat: runtime.Decimal | null
  carbs: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RecipeNutritionCountAggregateOutputType = {
  id: number
  recipeId: number
  calories: number
  protein: number
  fat: number
  carbs: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type RecipeNutritionAvgAggregateInputType = {
  calories?: true
  protein?: true
  fat?: true
  carbs?: true
}

export type RecipeNutritionSumAggregateInputType = {
  calories?: true
  protein?: true
  fat?: true
  carbs?: true
}

export type RecipeNutritionMinAggregateInputType = {
  id?: true
  recipeId?: true
  calories?: true
  protein?: true
  fat?: true
  carbs?: true
  createdAt?: true
  updatedAt?: true
}

export type RecipeNutritionMaxAggregateInputType = {
  id?: true
  recipeId?: true
  calories?: true
  protein?: true
  fat?: true
  carbs?: true
  createdAt?: true
  updatedAt?: true
}

export type RecipeNutritionCountAggregateInputType = {
  id?: true
  recipeId?: true
  calories?: true
  protein?: true
  fat?: true
  carbs?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type RecipeNutritionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecipeNutrition to aggregate.
   */
  where?: Prisma.RecipeNutritionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipeNutritions to fetch.
   */
  orderBy?: Prisma.RecipeNutritionOrderByWithRelationInput | Prisma.RecipeNutritionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RecipeNutritionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipeNutritions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipeNutritions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RecipeNutritions
  **/
  _count?: true | RecipeNutritionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RecipeNutritionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RecipeNutritionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RecipeNutritionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RecipeNutritionMaxAggregateInputType
}

export type GetRecipeNutritionAggregateType<T extends RecipeNutritionAggregateArgs> = {
      [P in keyof T & keyof AggregateRecipeNutrition]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRecipeNutrition[P]>
    : Prisma.GetScalarType<T[P], AggregateRecipeNutrition[P]>
}




export type RecipeNutritionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecipeNutritionWhereInput
  orderBy?: Prisma.RecipeNutritionOrderByWithAggregationInput | Prisma.RecipeNutritionOrderByWithAggregationInput[]
  by: Prisma.RecipeNutritionScalarFieldEnum[] | Prisma.RecipeNutritionScalarFieldEnum
  having?: Prisma.RecipeNutritionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RecipeNutritionCountAggregateInputType | true
  _avg?: RecipeNutritionAvgAggregateInputType
  _sum?: RecipeNutritionSumAggregateInputType
  _min?: RecipeNutritionMinAggregateInputType
  _max?: RecipeNutritionMaxAggregateInputType
}

export type RecipeNutritionGroupByOutputType = {
  id: string
  recipeId: string
  calories: number
  protein: runtime.Decimal
  fat: runtime.Decimal
  carbs: runtime.Decimal
  createdAt: Date
  updatedAt: Date
  _count: RecipeNutritionCountAggregateOutputType | null
  _avg: RecipeNutritionAvgAggregateOutputType | null
  _sum: RecipeNutritionSumAggregateOutputType | null
  _min: RecipeNutritionMinAggregateOutputType | null
  _max: RecipeNutritionMaxAggregateOutputType | null
}

export type GetRecipeNutritionGroupByPayload<T extends RecipeNutritionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RecipeNutritionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RecipeNutritionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RecipeNutritionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RecipeNutritionGroupByOutputType[P]>
      }
    >
  >



export type RecipeNutritionWhereInput = {
  AND?: Prisma.RecipeNutritionWhereInput | Prisma.RecipeNutritionWhereInput[]
  OR?: Prisma.RecipeNutritionWhereInput[]
  NOT?: Prisma.RecipeNutritionWhereInput | Prisma.RecipeNutritionWhereInput[]
  id?: Prisma.StringFilter<"RecipeNutrition"> | string
  recipeId?: Prisma.StringFilter<"RecipeNutrition"> | string
  calories?: Prisma.IntFilter<"RecipeNutrition"> | number
  protein?: Prisma.DecimalFilter<"RecipeNutrition"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  fat?: Prisma.DecimalFilter<"RecipeNutrition"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  carbs?: Prisma.DecimalFilter<"RecipeNutrition"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"RecipeNutrition"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RecipeNutrition"> | Date | string
  recipe?: Prisma.XOR<Prisma.RecipeScalarRelationFilter, Prisma.RecipeWhereInput>
}

export type RecipeNutritionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  recipeId?: Prisma.SortOrder
  calories?: Prisma.SortOrder
  protein?: Prisma.SortOrder
  fat?: Prisma.SortOrder
  carbs?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  recipe?: Prisma.RecipeOrderByWithRelationInput
}

export type RecipeNutritionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  recipeId?: string
  AND?: Prisma.RecipeNutritionWhereInput | Prisma.RecipeNutritionWhereInput[]
  OR?: Prisma.RecipeNutritionWhereInput[]
  NOT?: Prisma.RecipeNutritionWhereInput | Prisma.RecipeNutritionWhereInput[]
  calories?: Prisma.IntFilter<"RecipeNutrition"> | number
  protein?: Prisma.DecimalFilter<"RecipeNutrition"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  fat?: Prisma.DecimalFilter<"RecipeNutrition"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  carbs?: Prisma.DecimalFilter<"RecipeNutrition"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"RecipeNutrition"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RecipeNutrition"> | Date | string
  recipe?: Prisma.XOR<Prisma.RecipeScalarRelationFilter, Prisma.RecipeWhereInput>
}, "id" | "recipeId">

export type RecipeNutritionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  recipeId?: Prisma.SortOrder
  calories?: Prisma.SortOrder
  protein?: Prisma.SortOrder
  fat?: Prisma.SortOrder
  carbs?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.RecipeNutritionCountOrderByAggregateInput
  _avg?: Prisma.RecipeNutritionAvgOrderByAggregateInput
  _max?: Prisma.RecipeNutritionMaxOrderByAggregateInput
  _min?: Prisma.RecipeNutritionMinOrderByAggregateInput
  _sum?: Prisma.RecipeNutritionSumOrderByAggregateInput
}

export type RecipeNutritionScalarWhereWithAggregatesInput = {
  AND?: Prisma.RecipeNutritionScalarWhereWithAggregatesInput | Prisma.RecipeNutritionScalarWhereWithAggregatesInput[]
  OR?: Prisma.RecipeNutritionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RecipeNutritionScalarWhereWithAggregatesInput | Prisma.RecipeNutritionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RecipeNutrition"> | string
  recipeId?: Prisma.StringWithAggregatesFilter<"RecipeNutrition"> | string
  calories?: Prisma.IntWithAggregatesFilter<"RecipeNutrition"> | number
  protein?: Prisma.DecimalWithAggregatesFilter<"RecipeNutrition"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  fat?: Prisma.DecimalWithAggregatesFilter<"RecipeNutrition"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  carbs?: Prisma.DecimalWithAggregatesFilter<"RecipeNutrition"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RecipeNutrition"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"RecipeNutrition"> | Date | string
}

export type RecipeNutritionCreateInput = {
  id?: string
  calories: number
  protein: runtime.Decimal | runtime.DecimalJsLike | number | string
  fat: runtime.Decimal | runtime.DecimalJsLike | number | string
  carbs: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  recipe: Prisma.RecipeCreateNestedOneWithoutNutritionInput
}

export type RecipeNutritionUncheckedCreateInput = {
  id?: string
  recipeId: string
  calories: number
  protein: runtime.Decimal | runtime.DecimalJsLike | number | string
  fat: runtime.Decimal | runtime.DecimalJsLike | number | string
  carbs: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecipeNutritionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  calories?: Prisma.IntFieldUpdateOperationsInput | number
  protein?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  carbs?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  recipe?: Prisma.RecipeUpdateOneRequiredWithoutNutritionNestedInput
}

export type RecipeNutritionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipeId?: Prisma.StringFieldUpdateOperationsInput | string
  calories?: Prisma.IntFieldUpdateOperationsInput | number
  protein?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  carbs?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecipeNutritionCreateManyInput = {
  id?: string
  recipeId: string
  calories: number
  protein: runtime.Decimal | runtime.DecimalJsLike | number | string
  fat: runtime.Decimal | runtime.DecimalJsLike | number | string
  carbs: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecipeNutritionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  calories?: Prisma.IntFieldUpdateOperationsInput | number
  protein?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  carbs?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecipeNutritionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipeId?: Prisma.StringFieldUpdateOperationsInput | string
  calories?: Prisma.IntFieldUpdateOperationsInput | number
  protein?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  carbs?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecipeNutritionNullableScalarRelationFilter = {
  is?: Prisma.RecipeNutritionWhereInput | null
  isNot?: Prisma.RecipeNutritionWhereInput | null
}

export type RecipeNutritionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  recipeId?: Prisma.SortOrder
  calories?: Prisma.SortOrder
  protein?: Prisma.SortOrder
  fat?: Prisma.SortOrder
  carbs?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RecipeNutritionAvgOrderByAggregateInput = {
  calories?: Prisma.SortOrder
  protein?: Prisma.SortOrder
  fat?: Prisma.SortOrder
  carbs?: Prisma.SortOrder
}

export type RecipeNutritionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  recipeId?: Prisma.SortOrder
  calories?: Prisma.SortOrder
  protein?: Prisma.SortOrder
  fat?: Prisma.SortOrder
  carbs?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RecipeNutritionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  recipeId?: Prisma.SortOrder
  calories?: Prisma.SortOrder
  protein?: Prisma.SortOrder
  fat?: Prisma.SortOrder
  carbs?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RecipeNutritionSumOrderByAggregateInput = {
  calories?: Prisma.SortOrder
  protein?: Prisma.SortOrder
  fat?: Prisma.SortOrder
  carbs?: Prisma.SortOrder
}

export type RecipeNutritionCreateNestedOneWithoutRecipeInput = {
  create?: Prisma.XOR<Prisma.RecipeNutritionCreateWithoutRecipeInput, Prisma.RecipeNutritionUncheckedCreateWithoutRecipeInput>
  connectOrCreate?: Prisma.RecipeNutritionCreateOrConnectWithoutRecipeInput
  connect?: Prisma.RecipeNutritionWhereUniqueInput
}

export type RecipeNutritionUncheckedCreateNestedOneWithoutRecipeInput = {
  create?: Prisma.XOR<Prisma.RecipeNutritionCreateWithoutRecipeInput, Prisma.RecipeNutritionUncheckedCreateWithoutRecipeInput>
  connectOrCreate?: Prisma.RecipeNutritionCreateOrConnectWithoutRecipeInput
  connect?: Prisma.RecipeNutritionWhereUniqueInput
}

export type RecipeNutritionUpdateOneWithoutRecipeNestedInput = {
  create?: Prisma.XOR<Prisma.RecipeNutritionCreateWithoutRecipeInput, Prisma.RecipeNutritionUncheckedCreateWithoutRecipeInput>
  connectOrCreate?: Prisma.RecipeNutritionCreateOrConnectWithoutRecipeInput
  upsert?: Prisma.RecipeNutritionUpsertWithoutRecipeInput
  disconnect?: Prisma.RecipeNutritionWhereInput | boolean
  delete?: Prisma.RecipeNutritionWhereInput | boolean
  connect?: Prisma.RecipeNutritionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RecipeNutritionUpdateToOneWithWhereWithoutRecipeInput, Prisma.RecipeNutritionUpdateWithoutRecipeInput>, Prisma.RecipeNutritionUncheckedUpdateWithoutRecipeInput>
}

export type RecipeNutritionUncheckedUpdateOneWithoutRecipeNestedInput = {
  create?: Prisma.XOR<Prisma.RecipeNutritionCreateWithoutRecipeInput, Prisma.RecipeNutritionUncheckedCreateWithoutRecipeInput>
  connectOrCreate?: Prisma.RecipeNutritionCreateOrConnectWithoutRecipeInput
  upsert?: Prisma.RecipeNutritionUpsertWithoutRecipeInput
  disconnect?: Prisma.RecipeNutritionWhereInput | boolean
  delete?: Prisma.RecipeNutritionWhereInput | boolean
  connect?: Prisma.RecipeNutritionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RecipeNutritionUpdateToOneWithWhereWithoutRecipeInput, Prisma.RecipeNutritionUpdateWithoutRecipeInput>, Prisma.RecipeNutritionUncheckedUpdateWithoutRecipeInput>
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type RecipeNutritionCreateWithoutRecipeInput = {
  id?: string
  calories: number
  protein: runtime.Decimal | runtime.DecimalJsLike | number | string
  fat: runtime.Decimal | runtime.DecimalJsLike | number | string
  carbs: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecipeNutritionUncheckedCreateWithoutRecipeInput = {
  id?: string
  calories: number
  protein: runtime.Decimal | runtime.DecimalJsLike | number | string
  fat: runtime.Decimal | runtime.DecimalJsLike | number | string
  carbs: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecipeNutritionCreateOrConnectWithoutRecipeInput = {
  where: Prisma.RecipeNutritionWhereUniqueInput
  create: Prisma.XOR<Prisma.RecipeNutritionCreateWithoutRecipeInput, Prisma.RecipeNutritionUncheckedCreateWithoutRecipeInput>
}

export type RecipeNutritionUpsertWithoutRecipeInput = {
  update: Prisma.XOR<Prisma.RecipeNutritionUpdateWithoutRecipeInput, Prisma.RecipeNutritionUncheckedUpdateWithoutRecipeInput>
  create: Prisma.XOR<Prisma.RecipeNutritionCreateWithoutRecipeInput, Prisma.RecipeNutritionUncheckedCreateWithoutRecipeInput>
  where?: Prisma.RecipeNutritionWhereInput
}

export type RecipeNutritionUpdateToOneWithWhereWithoutRecipeInput = {
  where?: Prisma.RecipeNutritionWhereInput
  data: Prisma.XOR<Prisma.RecipeNutritionUpdateWithoutRecipeInput, Prisma.RecipeNutritionUncheckedUpdateWithoutRecipeInput>
}

export type RecipeNutritionUpdateWithoutRecipeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  calories?: Prisma.IntFieldUpdateOperationsInput | number
  protein?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  carbs?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecipeNutritionUncheckedUpdateWithoutRecipeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  calories?: Prisma.IntFieldUpdateOperationsInput | number
  protein?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  carbs?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type RecipeNutritionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  recipeId?: boolean
  calories?: boolean
  protein?: boolean
  fat?: boolean
  carbs?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipeNutrition"]>

export type RecipeNutritionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  recipeId?: boolean
  calories?: boolean
  protein?: boolean
  fat?: boolean
  carbs?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipeNutrition"]>

export type RecipeNutritionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  recipeId?: boolean
  calories?: boolean
  protein?: boolean
  fat?: boolean
  carbs?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipeNutrition"]>

export type RecipeNutritionSelectScalar = {
  id?: boolean
  recipeId?: boolean
  calories?: boolean
  protein?: boolean
  fat?: boolean
  carbs?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type RecipeNutritionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "recipeId" | "calories" | "protein" | "fat" | "carbs" | "createdAt" | "updatedAt", ExtArgs["result"]["recipeNutrition"]>
export type RecipeNutritionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}
export type RecipeNutritionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}
export type RecipeNutritionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}

export type $RecipeNutritionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RecipeNutrition"
  objects: {
    recipe: Prisma.$RecipePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    recipeId: string
    calories: number
    protein: runtime.Decimal
    fat: runtime.Decimal
    carbs: runtime.Decimal
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["recipeNutrition"]>
  composites: {}
}

export type RecipeNutritionGetPayload<S extends boolean | null | undefined | RecipeNutritionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RecipeNutritionPayload, S>

export type RecipeNutritionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RecipeNutritionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RecipeNutritionCountAggregateInputType | true
  }

export interface RecipeNutritionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RecipeNutrition'], meta: { name: 'RecipeNutrition' } }
  /**
   * Find zero or one RecipeNutrition that matches the filter.
   * @param {RecipeNutritionFindUniqueArgs} args - Arguments to find a RecipeNutrition
   * @example
   * // Get one RecipeNutrition
   * const recipeNutrition = await prisma.recipeNutrition.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RecipeNutritionFindUniqueArgs>(args: Prisma.SelectSubset<T, RecipeNutritionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RecipeNutritionClient<runtime.Types.Result.GetResult<Prisma.$RecipeNutritionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RecipeNutrition that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RecipeNutritionFindUniqueOrThrowArgs} args - Arguments to find a RecipeNutrition
   * @example
   * // Get one RecipeNutrition
   * const recipeNutrition = await prisma.recipeNutrition.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RecipeNutritionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RecipeNutritionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecipeNutritionClient<runtime.Types.Result.GetResult<Prisma.$RecipeNutritionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecipeNutrition that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeNutritionFindFirstArgs} args - Arguments to find a RecipeNutrition
   * @example
   * // Get one RecipeNutrition
   * const recipeNutrition = await prisma.recipeNutrition.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RecipeNutritionFindFirstArgs>(args?: Prisma.SelectSubset<T, RecipeNutritionFindFirstArgs<ExtArgs>>): Prisma.Prisma__RecipeNutritionClient<runtime.Types.Result.GetResult<Prisma.$RecipeNutritionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecipeNutrition that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeNutritionFindFirstOrThrowArgs} args - Arguments to find a RecipeNutrition
   * @example
   * // Get one RecipeNutrition
   * const recipeNutrition = await prisma.recipeNutrition.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RecipeNutritionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RecipeNutritionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecipeNutritionClient<runtime.Types.Result.GetResult<Prisma.$RecipeNutritionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RecipeNutritions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeNutritionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RecipeNutritions
   * const recipeNutritions = await prisma.recipeNutrition.findMany()
   * 
   * // Get first 10 RecipeNutritions
   * const recipeNutritions = await prisma.recipeNutrition.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const recipeNutritionWithIdOnly = await prisma.recipeNutrition.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RecipeNutritionFindManyArgs>(args?: Prisma.SelectSubset<T, RecipeNutritionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipeNutritionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RecipeNutrition.
   * @param {RecipeNutritionCreateArgs} args - Arguments to create a RecipeNutrition.
   * @example
   * // Create one RecipeNutrition
   * const RecipeNutrition = await prisma.recipeNutrition.create({
   *   data: {
   *     // ... data to create a RecipeNutrition
   *   }
   * })
   * 
   */
  create<T extends RecipeNutritionCreateArgs>(args: Prisma.SelectSubset<T, RecipeNutritionCreateArgs<ExtArgs>>): Prisma.Prisma__RecipeNutritionClient<runtime.Types.Result.GetResult<Prisma.$RecipeNutritionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RecipeNutritions.
   * @param {RecipeNutritionCreateManyArgs} args - Arguments to create many RecipeNutritions.
   * @example
   * // Create many RecipeNutritions
   * const recipeNutrition = await prisma.recipeNutrition.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RecipeNutritionCreateManyArgs>(args?: Prisma.SelectSubset<T, RecipeNutritionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RecipeNutritions and returns the data saved in the database.
   * @param {RecipeNutritionCreateManyAndReturnArgs} args - Arguments to create many RecipeNutritions.
   * @example
   * // Create many RecipeNutritions
   * const recipeNutrition = await prisma.recipeNutrition.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RecipeNutritions and only return the `id`
   * const recipeNutritionWithIdOnly = await prisma.recipeNutrition.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RecipeNutritionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RecipeNutritionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipeNutritionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RecipeNutrition.
   * @param {RecipeNutritionDeleteArgs} args - Arguments to delete one RecipeNutrition.
   * @example
   * // Delete one RecipeNutrition
   * const RecipeNutrition = await prisma.recipeNutrition.delete({
   *   where: {
   *     // ... filter to delete one RecipeNutrition
   *   }
   * })
   * 
   */
  delete<T extends RecipeNutritionDeleteArgs>(args: Prisma.SelectSubset<T, RecipeNutritionDeleteArgs<ExtArgs>>): Prisma.Prisma__RecipeNutritionClient<runtime.Types.Result.GetResult<Prisma.$RecipeNutritionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RecipeNutrition.
   * @param {RecipeNutritionUpdateArgs} args - Arguments to update one RecipeNutrition.
   * @example
   * // Update one RecipeNutrition
   * const recipeNutrition = await prisma.recipeNutrition.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RecipeNutritionUpdateArgs>(args: Prisma.SelectSubset<T, RecipeNutritionUpdateArgs<ExtArgs>>): Prisma.Prisma__RecipeNutritionClient<runtime.Types.Result.GetResult<Prisma.$RecipeNutritionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RecipeNutritions.
   * @param {RecipeNutritionDeleteManyArgs} args - Arguments to filter RecipeNutritions to delete.
   * @example
   * // Delete a few RecipeNutritions
   * const { count } = await prisma.recipeNutrition.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RecipeNutritionDeleteManyArgs>(args?: Prisma.SelectSubset<T, RecipeNutritionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecipeNutritions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeNutritionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RecipeNutritions
   * const recipeNutrition = await prisma.recipeNutrition.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RecipeNutritionUpdateManyArgs>(args: Prisma.SelectSubset<T, RecipeNutritionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecipeNutritions and returns the data updated in the database.
   * @param {RecipeNutritionUpdateManyAndReturnArgs} args - Arguments to update many RecipeNutritions.
   * @example
   * // Update many RecipeNutritions
   * const recipeNutrition = await prisma.recipeNutrition.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RecipeNutritions and only return the `id`
   * const recipeNutritionWithIdOnly = await prisma.recipeNutrition.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RecipeNutritionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RecipeNutritionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipeNutritionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RecipeNutrition.
   * @param {RecipeNutritionUpsertArgs} args - Arguments to update or create a RecipeNutrition.
   * @example
   * // Update or create a RecipeNutrition
   * const recipeNutrition = await prisma.recipeNutrition.upsert({
   *   create: {
   *     // ... data to create a RecipeNutrition
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RecipeNutrition we want to update
   *   }
   * })
   */
  upsert<T extends RecipeNutritionUpsertArgs>(args: Prisma.SelectSubset<T, RecipeNutritionUpsertArgs<ExtArgs>>): Prisma.Prisma__RecipeNutritionClient<runtime.Types.Result.GetResult<Prisma.$RecipeNutritionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RecipeNutritions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeNutritionCountArgs} args - Arguments to filter RecipeNutritions to count.
   * @example
   * // Count the number of RecipeNutritions
   * const count = await prisma.recipeNutrition.count({
   *   where: {
   *     // ... the filter for the RecipeNutritions we want to count
   *   }
   * })
  **/
  count<T extends RecipeNutritionCountArgs>(
    args?: Prisma.Subset<T, RecipeNutritionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RecipeNutritionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RecipeNutrition.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeNutritionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RecipeNutritionAggregateArgs>(args: Prisma.Subset<T, RecipeNutritionAggregateArgs>): Prisma.PrismaPromise<GetRecipeNutritionAggregateType<T>>

  /**
   * Group by RecipeNutrition.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeNutritionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RecipeNutritionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RecipeNutritionGroupByArgs['orderBy'] }
      : { orderBy?: RecipeNutritionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RecipeNutritionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRecipeNutritionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RecipeNutrition model
 */
readonly fields: RecipeNutritionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RecipeNutrition.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RecipeNutritionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  recipe<T extends Prisma.RecipeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RecipeDefaultArgs<ExtArgs>>): Prisma.Prisma__RecipeClient<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RecipeNutrition model
 */
export interface RecipeNutritionFieldRefs {
  readonly id: Prisma.FieldRef<"RecipeNutrition", 'String'>
  readonly recipeId: Prisma.FieldRef<"RecipeNutrition", 'String'>
  readonly calories: Prisma.FieldRef<"RecipeNutrition", 'Int'>
  readonly protein: Prisma.FieldRef<"RecipeNutrition", 'Decimal'>
  readonly fat: Prisma.FieldRef<"RecipeNutrition", 'Decimal'>
  readonly carbs: Prisma.FieldRef<"RecipeNutrition", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"RecipeNutrition", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"RecipeNutrition", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RecipeNutrition findUnique
 */
export type RecipeNutritionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeNutrition
   */
  select?: Prisma.RecipeNutritionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeNutrition
   */
  omit?: Prisma.RecipeNutritionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeNutritionInclude<ExtArgs> | null
  /**
   * Filter, which RecipeNutrition to fetch.
   */
  where: Prisma.RecipeNutritionWhereUniqueInput
}

/**
 * RecipeNutrition findUniqueOrThrow
 */
export type RecipeNutritionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeNutrition
   */
  select?: Prisma.RecipeNutritionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeNutrition
   */
  omit?: Prisma.RecipeNutritionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeNutritionInclude<ExtArgs> | null
  /**
   * Filter, which RecipeNutrition to fetch.
   */
  where: Prisma.RecipeNutritionWhereUniqueInput
}

/**
 * RecipeNutrition findFirst
 */
export type RecipeNutritionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeNutrition
   */
  select?: Prisma.RecipeNutritionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeNutrition
   */
  omit?: Prisma.RecipeNutritionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeNutritionInclude<ExtArgs> | null
  /**
   * Filter, which RecipeNutrition to fetch.
   */
  where?: Prisma.RecipeNutritionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipeNutritions to fetch.
   */
  orderBy?: Prisma.RecipeNutritionOrderByWithRelationInput | Prisma.RecipeNutritionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecipeNutritions.
   */
  cursor?: Prisma.RecipeNutritionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipeNutritions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipeNutritions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecipeNutritions.
   */
  distinct?: Prisma.RecipeNutritionScalarFieldEnum | Prisma.RecipeNutritionScalarFieldEnum[]
}

/**
 * RecipeNutrition findFirstOrThrow
 */
export type RecipeNutritionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeNutrition
   */
  select?: Prisma.RecipeNutritionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeNutrition
   */
  omit?: Prisma.RecipeNutritionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeNutritionInclude<ExtArgs> | null
  /**
   * Filter, which RecipeNutrition to fetch.
   */
  where?: Prisma.RecipeNutritionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipeNutritions to fetch.
   */
  orderBy?: Prisma.RecipeNutritionOrderByWithRelationInput | Prisma.RecipeNutritionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecipeNutritions.
   */
  cursor?: Prisma.RecipeNutritionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipeNutritions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipeNutritions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecipeNutritions.
   */
  distinct?: Prisma.RecipeNutritionScalarFieldEnum | Prisma.RecipeNutritionScalarFieldEnum[]
}

/**
 * RecipeNutrition findMany
 */
export type RecipeNutritionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeNutrition
   */
  select?: Prisma.RecipeNutritionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeNutrition
   */
  omit?: Prisma.RecipeNutritionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeNutritionInclude<ExtArgs> | null
  /**
   * Filter, which RecipeNutritions to fetch.
   */
  where?: Prisma.RecipeNutritionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipeNutritions to fetch.
   */
  orderBy?: Prisma.RecipeNutritionOrderByWithRelationInput | Prisma.RecipeNutritionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RecipeNutritions.
   */
  cursor?: Prisma.RecipeNutritionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipeNutritions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipeNutritions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecipeNutritions.
   */
  distinct?: Prisma.RecipeNutritionScalarFieldEnum | Prisma.RecipeNutritionScalarFieldEnum[]
}

/**
 * RecipeNutrition create
 */
export type RecipeNutritionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeNutrition
   */
  select?: Prisma.RecipeNutritionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeNutrition
   */
  omit?: Prisma.RecipeNutritionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeNutritionInclude<ExtArgs> | null
  /**
   * The data needed to create a RecipeNutrition.
   */
  data: Prisma.XOR<Prisma.RecipeNutritionCreateInput, Prisma.RecipeNutritionUncheckedCreateInput>
}

/**
 * RecipeNutrition createMany
 */
export type RecipeNutritionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RecipeNutritions.
   */
  data: Prisma.RecipeNutritionCreateManyInput | Prisma.RecipeNutritionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RecipeNutrition createManyAndReturn
 */
export type RecipeNutritionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeNutrition
   */
  select?: Prisma.RecipeNutritionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeNutrition
   */
  omit?: Prisma.RecipeNutritionOmit<ExtArgs> | null
  /**
   * The data used to create many RecipeNutritions.
   */
  data: Prisma.RecipeNutritionCreateManyInput | Prisma.RecipeNutritionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeNutritionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RecipeNutrition update
 */
export type RecipeNutritionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeNutrition
   */
  select?: Prisma.RecipeNutritionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeNutrition
   */
  omit?: Prisma.RecipeNutritionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeNutritionInclude<ExtArgs> | null
  /**
   * The data needed to update a RecipeNutrition.
   */
  data: Prisma.XOR<Prisma.RecipeNutritionUpdateInput, Prisma.RecipeNutritionUncheckedUpdateInput>
  /**
   * Choose, which RecipeNutrition to update.
   */
  where: Prisma.RecipeNutritionWhereUniqueInput
}

/**
 * RecipeNutrition updateMany
 */
export type RecipeNutritionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RecipeNutritions.
   */
  data: Prisma.XOR<Prisma.RecipeNutritionUpdateManyMutationInput, Prisma.RecipeNutritionUncheckedUpdateManyInput>
  /**
   * Filter which RecipeNutritions to update
   */
  where?: Prisma.RecipeNutritionWhereInput
  /**
   * Limit how many RecipeNutritions to update.
   */
  limit?: number
}

/**
 * RecipeNutrition updateManyAndReturn
 */
export type RecipeNutritionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeNutrition
   */
  select?: Prisma.RecipeNutritionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeNutrition
   */
  omit?: Prisma.RecipeNutritionOmit<ExtArgs> | null
  /**
   * The data used to update RecipeNutritions.
   */
  data: Prisma.XOR<Prisma.RecipeNutritionUpdateManyMutationInput, Prisma.RecipeNutritionUncheckedUpdateManyInput>
  /**
   * Filter which RecipeNutritions to update
   */
  where?: Prisma.RecipeNutritionWhereInput
  /**
   * Limit how many RecipeNutritions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeNutritionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RecipeNutrition upsert
 */
export type RecipeNutritionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeNutrition
   */
  select?: Prisma.RecipeNutritionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeNutrition
   */
  omit?: Prisma.RecipeNutritionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeNutritionInclude<ExtArgs> | null
  /**
   * The filter to search for the RecipeNutrition to update in case it exists.
   */
  where: Prisma.RecipeNutritionWhereUniqueInput
  /**
   * In case the RecipeNutrition found by the `where` argument doesn't exist, create a new RecipeNutrition with this data.
   */
  create: Prisma.XOR<Prisma.RecipeNutritionCreateInput, Prisma.RecipeNutritionUncheckedCreateInput>
  /**
   * In case the RecipeNutrition was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RecipeNutritionUpdateInput, Prisma.RecipeNutritionUncheckedUpdateInput>
}

/**
 * RecipeNutrition delete
 */
export type RecipeNutritionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeNutrition
   */
  select?: Prisma.RecipeNutritionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeNutrition
   */
  omit?: Prisma.RecipeNutritionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeNutritionInclude<ExtArgs> | null
  /**
   * Filter which RecipeNutrition to delete.
   */
  where: Prisma.RecipeNutritionWhereUniqueInput
}

/**
 * RecipeNutrition deleteMany
 */
export type RecipeNutritionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecipeNutritions to delete
   */
  where?: Prisma.RecipeNutritionWhereInput
  /**
   * Limit how many RecipeNutritions to delete.
   */
  limit?: number
}

/**
 * RecipeNutrition without action
 */
export type RecipeNutritionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeNutrition
   */
  select?: Prisma.RecipeNutritionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeNutrition
   */
  omit?: Prisma.RecipeNutritionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeNutritionInclude<ExtArgs> | null
}
