
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  User: 'User',
  Recipe: 'Recipe',
  RecipeNutrition: 'RecipeNutrition',
  Ingredient: 'Ingredient',
  MeasurementUnit: 'MeasurementUnit',
  RecipeIngredient: 'RecipeIngredient',
  RecipeIngredientGroup: 'RecipeIngredientGroup',
  RecipeEquipment: 'RecipeEquipment',
  RecipeStep: 'RecipeStep',
  RecipeComment: 'RecipeComment'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "user" | "recipe" | "recipeNutrition" | "ingredient" | "measurementUnit" | "recipeIngredient" | "recipeIngredientGroup" | "recipeEquipment" | "recipeStep" | "recipeComment"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    Recipe: {
      payload: Prisma.$RecipePayload<ExtArgs>
      fields: Prisma.RecipeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RecipeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RecipeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>
        }
        findFirst: {
          args: Prisma.RecipeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RecipeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>
        }
        findMany: {
          args: Prisma.RecipeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>[]
        }
        create: {
          args: Prisma.RecipeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>
        }
        createMany: {
          args: Prisma.RecipeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RecipeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>[]
        }
        delete: {
          args: Prisma.RecipeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>
        }
        update: {
          args: Prisma.RecipeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>
        }
        deleteMany: {
          args: Prisma.RecipeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RecipeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RecipeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>[]
        }
        upsert: {
          args: Prisma.RecipeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>
        }
        aggregate: {
          args: Prisma.RecipeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRecipe>
        }
        groupBy: {
          args: Prisma.RecipeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeGroupByOutputType>[]
        }
        count: {
          args: Prisma.RecipeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeCountAggregateOutputType> | number
        }
      }
    }
    RecipeNutrition: {
      payload: Prisma.$RecipeNutritionPayload<ExtArgs>
      fields: Prisma.RecipeNutritionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RecipeNutritionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeNutritionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RecipeNutritionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeNutritionPayload>
        }
        findFirst: {
          args: Prisma.RecipeNutritionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeNutritionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RecipeNutritionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeNutritionPayload>
        }
        findMany: {
          args: Prisma.RecipeNutritionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeNutritionPayload>[]
        }
        create: {
          args: Prisma.RecipeNutritionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeNutritionPayload>
        }
        createMany: {
          args: Prisma.RecipeNutritionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RecipeNutritionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeNutritionPayload>[]
        }
        delete: {
          args: Prisma.RecipeNutritionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeNutritionPayload>
        }
        update: {
          args: Prisma.RecipeNutritionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeNutritionPayload>
        }
        deleteMany: {
          args: Prisma.RecipeNutritionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RecipeNutritionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RecipeNutritionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeNutritionPayload>[]
        }
        upsert: {
          args: Prisma.RecipeNutritionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeNutritionPayload>
        }
        aggregate: {
          args: Prisma.RecipeNutritionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRecipeNutrition>
        }
        groupBy: {
          args: Prisma.RecipeNutritionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeNutritionGroupByOutputType>[]
        }
        count: {
          args: Prisma.RecipeNutritionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeNutritionCountAggregateOutputType> | number
        }
      }
    }
    Ingredient: {
      payload: Prisma.$IngredientPayload<ExtArgs>
      fields: Prisma.IngredientFieldRefs
      operations: {
        findUnique: {
          args: Prisma.IngredientFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.IngredientFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>
        }
        findFirst: {
          args: Prisma.IngredientFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.IngredientFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>
        }
        findMany: {
          args: Prisma.IngredientFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>[]
        }
        create: {
          args: Prisma.IngredientCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>
        }
        createMany: {
          args: Prisma.IngredientCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.IngredientCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>[]
        }
        delete: {
          args: Prisma.IngredientDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>
        }
        update: {
          args: Prisma.IngredientUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>
        }
        deleteMany: {
          args: Prisma.IngredientDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.IngredientUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.IngredientUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>[]
        }
        upsert: {
          args: Prisma.IngredientUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>
        }
        aggregate: {
          args: Prisma.IngredientAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateIngredient>
        }
        groupBy: {
          args: Prisma.IngredientGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IngredientGroupByOutputType>[]
        }
        count: {
          args: Prisma.IngredientCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IngredientCountAggregateOutputType> | number
        }
      }
    }
    MeasurementUnit: {
      payload: Prisma.$MeasurementUnitPayload<ExtArgs>
      fields: Prisma.MeasurementUnitFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MeasurementUnitFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MeasurementUnitPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MeasurementUnitFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MeasurementUnitPayload>
        }
        findFirst: {
          args: Prisma.MeasurementUnitFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MeasurementUnitPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MeasurementUnitFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MeasurementUnitPayload>
        }
        findMany: {
          args: Prisma.MeasurementUnitFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MeasurementUnitPayload>[]
        }
        create: {
          args: Prisma.MeasurementUnitCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MeasurementUnitPayload>
        }
        createMany: {
          args: Prisma.MeasurementUnitCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MeasurementUnitCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MeasurementUnitPayload>[]
        }
        delete: {
          args: Prisma.MeasurementUnitDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MeasurementUnitPayload>
        }
        update: {
          args: Prisma.MeasurementUnitUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MeasurementUnitPayload>
        }
        deleteMany: {
          args: Prisma.MeasurementUnitDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MeasurementUnitUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MeasurementUnitUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MeasurementUnitPayload>[]
        }
        upsert: {
          args: Prisma.MeasurementUnitUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MeasurementUnitPayload>
        }
        aggregate: {
          args: Prisma.MeasurementUnitAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMeasurementUnit>
        }
        groupBy: {
          args: Prisma.MeasurementUnitGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MeasurementUnitGroupByOutputType>[]
        }
        count: {
          args: Prisma.MeasurementUnitCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MeasurementUnitCountAggregateOutputType> | number
        }
      }
    }
    RecipeIngredient: {
      payload: Prisma.$RecipeIngredientPayload<ExtArgs>
      fields: Prisma.RecipeIngredientFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RecipeIngredientFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RecipeIngredientFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientPayload>
        }
        findFirst: {
          args: Prisma.RecipeIngredientFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RecipeIngredientFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientPayload>
        }
        findMany: {
          args: Prisma.RecipeIngredientFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientPayload>[]
        }
        create: {
          args: Prisma.RecipeIngredientCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientPayload>
        }
        createMany: {
          args: Prisma.RecipeIngredientCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RecipeIngredientCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientPayload>[]
        }
        delete: {
          args: Prisma.RecipeIngredientDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientPayload>
        }
        update: {
          args: Prisma.RecipeIngredientUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientPayload>
        }
        deleteMany: {
          args: Prisma.RecipeIngredientDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RecipeIngredientUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RecipeIngredientUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientPayload>[]
        }
        upsert: {
          args: Prisma.RecipeIngredientUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientPayload>
        }
        aggregate: {
          args: Prisma.RecipeIngredientAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRecipeIngredient>
        }
        groupBy: {
          args: Prisma.RecipeIngredientGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeIngredientGroupByOutputType>[]
        }
        count: {
          args: Prisma.RecipeIngredientCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeIngredientCountAggregateOutputType> | number
        }
      }
    }
    RecipeIngredientGroup: {
      payload: Prisma.$RecipeIngredientGroupPayload<ExtArgs>
      fields: Prisma.RecipeIngredientGroupFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RecipeIngredientGroupFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientGroupPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RecipeIngredientGroupFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientGroupPayload>
        }
        findFirst: {
          args: Prisma.RecipeIngredientGroupFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientGroupPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RecipeIngredientGroupFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientGroupPayload>
        }
        findMany: {
          args: Prisma.RecipeIngredientGroupFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientGroupPayload>[]
        }
        create: {
          args: Prisma.RecipeIngredientGroupCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientGroupPayload>
        }
        createMany: {
          args: Prisma.RecipeIngredientGroupCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RecipeIngredientGroupCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientGroupPayload>[]
        }
        delete: {
          args: Prisma.RecipeIngredientGroupDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientGroupPayload>
        }
        update: {
          args: Prisma.RecipeIngredientGroupUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientGroupPayload>
        }
        deleteMany: {
          args: Prisma.RecipeIngredientGroupDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RecipeIngredientGroupUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RecipeIngredientGroupUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientGroupPayload>[]
        }
        upsert: {
          args: Prisma.RecipeIngredientGroupUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeIngredientGroupPayload>
        }
        aggregate: {
          args: Prisma.RecipeIngredientGroupAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRecipeIngredientGroup>
        }
        groupBy: {
          args: Prisma.RecipeIngredientGroupGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeIngredientGroupGroupByOutputType>[]
        }
        count: {
          args: Prisma.RecipeIngredientGroupCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeIngredientGroupCountAggregateOutputType> | number
        }
      }
    }
    RecipeEquipment: {
      payload: Prisma.$RecipeEquipmentPayload<ExtArgs>
      fields: Prisma.RecipeEquipmentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RecipeEquipmentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeEquipmentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RecipeEquipmentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeEquipmentPayload>
        }
        findFirst: {
          args: Prisma.RecipeEquipmentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeEquipmentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RecipeEquipmentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeEquipmentPayload>
        }
        findMany: {
          args: Prisma.RecipeEquipmentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeEquipmentPayload>[]
        }
        create: {
          args: Prisma.RecipeEquipmentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeEquipmentPayload>
        }
        createMany: {
          args: Prisma.RecipeEquipmentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RecipeEquipmentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeEquipmentPayload>[]
        }
        delete: {
          args: Prisma.RecipeEquipmentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeEquipmentPayload>
        }
        update: {
          args: Prisma.RecipeEquipmentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeEquipmentPayload>
        }
        deleteMany: {
          args: Prisma.RecipeEquipmentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RecipeEquipmentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RecipeEquipmentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeEquipmentPayload>[]
        }
        upsert: {
          args: Prisma.RecipeEquipmentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeEquipmentPayload>
        }
        aggregate: {
          args: Prisma.RecipeEquipmentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRecipeEquipment>
        }
        groupBy: {
          args: Prisma.RecipeEquipmentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeEquipmentGroupByOutputType>[]
        }
        count: {
          args: Prisma.RecipeEquipmentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeEquipmentCountAggregateOutputType> | number
        }
      }
    }
    RecipeStep: {
      payload: Prisma.$RecipeStepPayload<ExtArgs>
      fields: Prisma.RecipeStepFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RecipeStepFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeStepPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RecipeStepFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeStepPayload>
        }
        findFirst: {
          args: Prisma.RecipeStepFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeStepPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RecipeStepFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeStepPayload>
        }
        findMany: {
          args: Prisma.RecipeStepFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeStepPayload>[]
        }
        create: {
          args: Prisma.RecipeStepCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeStepPayload>
        }
        createMany: {
          args: Prisma.RecipeStepCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RecipeStepCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeStepPayload>[]
        }
        delete: {
          args: Prisma.RecipeStepDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeStepPayload>
        }
        update: {
          args: Prisma.RecipeStepUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeStepPayload>
        }
        deleteMany: {
          args: Prisma.RecipeStepDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RecipeStepUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RecipeStepUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeStepPayload>[]
        }
        upsert: {
          args: Prisma.RecipeStepUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeStepPayload>
        }
        aggregate: {
          args: Prisma.RecipeStepAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRecipeStep>
        }
        groupBy: {
          args: Prisma.RecipeStepGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeStepGroupByOutputType>[]
        }
        count: {
          args: Prisma.RecipeStepCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeStepCountAggregateOutputType> | number
        }
      }
    }
    RecipeComment: {
      payload: Prisma.$RecipeCommentPayload<ExtArgs>
      fields: Prisma.RecipeCommentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RecipeCommentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeCommentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RecipeCommentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeCommentPayload>
        }
        findFirst: {
          args: Prisma.RecipeCommentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeCommentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RecipeCommentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeCommentPayload>
        }
        findMany: {
          args: Prisma.RecipeCommentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeCommentPayload>[]
        }
        create: {
          args: Prisma.RecipeCommentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeCommentPayload>
        }
        createMany: {
          args: Prisma.RecipeCommentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RecipeCommentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeCommentPayload>[]
        }
        delete: {
          args: Prisma.RecipeCommentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeCommentPayload>
        }
        update: {
          args: Prisma.RecipeCommentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeCommentPayload>
        }
        deleteMany: {
          args: Prisma.RecipeCommentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RecipeCommentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RecipeCommentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeCommentPayload>[]
        }
        upsert: {
          args: Prisma.RecipeCommentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeCommentPayload>
        }
        aggregate: {
          args: Prisma.RecipeCommentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRecipeComment>
        }
        groupBy: {
          args: Prisma.RecipeCommentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeCommentGroupByOutputType>[]
        }
        count: {
          args: Prisma.RecipeCommentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeCommentCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const RecipeScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  image: 'image',
  authorId: 'authorId',
  outputQuantity: 'outputQuantity',
  outputUnitId: 'outputUnitId',
  servings: 'servings',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RecipeScalarFieldEnum = (typeof RecipeScalarFieldEnum)[keyof typeof RecipeScalarFieldEnum]


export const RecipeNutritionScalarFieldEnum = {
  id: 'id',
  recipeId: 'recipeId',
  calories: 'calories',
  protein: 'protein',
  fat: 'fat',
  carbs: 'carbs',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RecipeNutritionScalarFieldEnum = (typeof RecipeNutritionScalarFieldEnum)[keyof typeof RecipeNutritionScalarFieldEnum]


export const IngredientScalarFieldEnum = {
  id: 'id',
  name: 'name',
  sticker: 'sticker',
  recipeId: 'recipeId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type IngredientScalarFieldEnum = (typeof IngredientScalarFieldEnum)[keyof typeof IngredientScalarFieldEnum]


export const MeasurementUnitScalarFieldEnum = {
  id: 'id',
  name: 'name',
  shortName: 'shortName',
  kind: 'kind',
  roundToInteger: 'roundToInteger',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MeasurementUnitScalarFieldEnum = (typeof MeasurementUnitScalarFieldEnum)[keyof typeof MeasurementUnitScalarFieldEnum]


export const RecipeIngredientScalarFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  ingredientId: 'ingredientId',
  unitId: 'unitId',
  order: 'order',
  quantity: 'quantity',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RecipeIngredientScalarFieldEnum = (typeof RecipeIngredientScalarFieldEnum)[keyof typeof RecipeIngredientScalarFieldEnum]


export const RecipeIngredientGroupScalarFieldEnum = {
  id: 'id',
  recipeId: 'recipeId',
  order: 'order',
  label: 'label',
  outputQuantity: 'outputQuantity',
  outputUnitId: 'outputUnitId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RecipeIngredientGroupScalarFieldEnum = (typeof RecipeIngredientGroupScalarFieldEnum)[keyof typeof RecipeIngredientGroupScalarFieldEnum]


export const RecipeEquipmentScalarFieldEnum = {
  id: 'id',
  recipeId: 'recipeId',
  order: 'order',
  label: 'label',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RecipeEquipmentScalarFieldEnum = (typeof RecipeEquipmentScalarFieldEnum)[keyof typeof RecipeEquipmentScalarFieldEnum]


export const RecipeStepScalarFieldEnum = {
  id: 'id',
  recipeId: 'recipeId',
  order: 'order',
  text: 'text',
  image: 'image',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RecipeStepScalarFieldEnum = (typeof RecipeStepScalarFieldEnum)[keyof typeof RecipeStepScalarFieldEnum]


export const RecipeCommentScalarFieldEnum = {
  id: 'id',
  recipeId: 'recipeId',
  order: 'order',
  initials: 'initials',
  name: 'name',
  text: 'text',
  label: 'label',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RecipeCommentScalarFieldEnum = (typeof RecipeCommentScalarFieldEnum)[keyof typeof RecipeCommentScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Decimal'
 */
export type DecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal'>
    


/**
 * Reference to a field of type 'Decimal[]'
 */
export type ListDecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'MeasurementUnitKind'
 */
export type EnumMeasurementUnitKindFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'MeasurementUnitKind'>
    


/**
 * Reference to a field of type 'MeasurementUnitKind[]'
 */
export type ListEnumMeasurementUnitKindFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'MeasurementUnitKind[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}
export type GlobalOmitConfig = {
  user?: Prisma.UserOmit
  recipe?: Prisma.RecipeOmit
  recipeNutrition?: Prisma.RecipeNutritionOmit
  ingredient?: Prisma.IngredientOmit
  measurementUnit?: Prisma.MeasurementUnitOmit
  recipeIngredient?: Prisma.RecipeIngredientOmit
  recipeIngredientGroup?: Prisma.RecipeIngredientGroupOmit
  recipeEquipment?: Prisma.RecipeEquipmentOmit
  recipeStep?: Prisma.RecipeStepOmit
  recipeComment?: Prisma.RecipeCommentOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

